# biencoder
# python finetune.py --per_device_train_batch_size 16384 --per_device_eval_batch_size 16384 --use_wandb 1 --bf16 1 --dataset nomic_unsupervised --sampling_strategy cluster_within_domain --exp_name biencoder-finetune-2--TEST --num_train_epochs 3 --learning_rate 2e-6 --embedder nomic-ai/nomic-embed-text-v1-unsupervised --dataset_embedder nomic-ai/nomic-embed-text-v1-unsupervised --clustering_model gtr_base --clustering_query_to_doc 1 --automatically_deduplicate_documents 1 --automatically_deduplicate_queries 1 --arch biencoder --dataset_info batch --ddp_find_unused_parameters 0 --torch_compile 0 --eval_rerank_topk 1024 --lr_scheduler_type cosine --warmup_steps 5600 --disable_dropout 1 --eval_steps 2000 --max_seq_length 512 --max_batch_size_fits_in_memory 128 --use_gc 1 --logging_steps 4 --train_cluster_size 16384 --eval_cluster_size 16384 --use_prefix 1 --transductive_corpus_size 1024 --save_steps 400 --logit_scale 50 --max_eval_batches 2 --use_wandb 0
# torchrun --nproc_per_node 8 finetune.py --per_device_train_batch_size 16384 --per_device_eval_batch_size 16384 --use_wandb 1 --bf16 1 --dataset nomic_unsupervised --sampling_strategy cluster_within_domain --exp_name biencoder-finetune-3 --num_train_epochs 3 --learning_rate 1e-6 --embedder nomic-ai/nomic-embed-text-v1-unsupervised --dataset_embedder nomic-ai/nomic-embed-text-v1-unsupervised --clustering_model gtr_base --clustering_query_to_doc 1 --automatically_deduplicate_documents 1 --automatically_deduplicate_queries 1 --arch biencoder --dataset_info batch --ddp_find_unused_parameters 0 --torch_compile 0 --eval_rerank_topk 1024 --lr_scheduler_type cosine --warmup_steps 5600 --disable_dropout 1 --eval_steps 2000 --max_seq_length 512 --max_batch_size_fits_in_memory 128 --use_gc 1 --logging_steps 4 --train_cluster_size 16384 --eval_cluster_size 16384 --use_prefix 1 --transductive_corpus_size 1024 --save_steps 400 --logit_scale 50 --max_eval_batches 2

# biencoder
# EXPERIMENT STILL TO RUN: v
torchrun --nproc_per_node 8 finetune.py --per_device_train_batch_size 16384 --per_device_eval_batch_size 16384 --use_wandb 1 --bf16 1 --dataset nomic_unsupervised --sampling_strategy domain --exp_name biencoder-finetune-4--domain --num_train_epochs 3 --learning_rate 1e-5 --embedder nomic-ai/nomic-embed-text-v1-unsupervised --dataset_embedder nomic-ai/nomic-embed-text-v1-unsupervised --clustering_model gtr_base --clustering_query_to_doc 1 --automatically_deduplicate_documents 1 --automatically_deduplicate_queries 1 --arch biencoder --dataset_info batch --ddp_find_unused_parameters 0 --torch_compile 0 --eval_rerank_topk 1024 --lr_scheduler_type cosine --warmup_steps 5600 --disable_dropout 1 --eval_steps 2000 --max_seq_length 512 --max_batch_size_fits_in_memory 128 --use_gc 1 --logging_steps 4 --train_cluster_size 16384 --eval_cluster_size 16384 --use_prefix 1 --transductive_corpus_size 1024 --save_steps 400 --logit_scale 50 --max_eval_batches 2


# transductive
# torchrun --nproc_per_node 8 finetune.py --per_device_train_batch_size 16384 --per_device_eval_batch_size 16384 --use_wandb 1 --bf16 1 --dataset nomic_unsupervised --sampling_strategy cluster_within_domain --exp_name transductive-finetune-3 --num_train_epochs 3 --learning_rate 1e-6 --embedder nomic-ai/nomic-embed-text-v1-unsupervised --dataset_embedder nomic-ai/nomic-embed-text-v1-unsupervised --clustering_model gtr_base --clustering_query_to_doc 1 --automatically_deduplicate_documents 1 --automatically_deduplicate_queries 1 --arch query_independent_dt --dataset_info batch --ddp_find_unused_parameters 0 --torch_compile 0 --eval_rerank_topk 1024 --lr_scheduler_type cosine --warmup_steps 5600 --disable_dropout 1 --eval_steps 2400 --max_seq_length 512 --max_batch_size_fits_in_memory 64 --use_gc 1 --logging_steps 4 --train_cluster_size 16384 --eval_cluster_size 16384 --use_prefix 1 --transductive_corpus_size 1024 --save_steps 400 --logit_scale 50 --max_eval_batches 2
torchrun --nproc_per_node 8 finetune.py --per_device_train_batch_size 16384 --per_device_eval_batch_size 16384 --use_wandb 1 --bf16 1 --dataset nomic_unsupervised --sampling_strategy domain --exp_name transductive-finetune-5--domain --num_train_epochs 3 --learning_rate 2e-5 --embedder nomic-ai/nomic-embed-text-v1-unsupervised --dataset_embedder nomic-ai/nomic-embed-text-v1-unsupervised --clustering_model gtr_base --clustering_query_to_doc 1 --automatically_deduplicate_documents 1 --automatically_deduplicate_queries 1 --arch query_independent_dt --dataset_info batch --ddp_find_unused_parameters 0 --torch_compile 0 --eval_rerank_topk 1024 --lr_scheduler_type cosine --warmup_steps 5600 --disable_dropout 1 --eval_steps 2400 --max_seq_length 512 --max_batch_size_fits_in_memory 64 --use_gc 1 --logging_steps 4 --train_cluster_size 16384 --eval_cluster_size 16384 --use_prefix 1 --transductive_corpus_size 1024 --save_steps 400 --logit_scale 50 --max_eval_batches 2

# torchrun --nproc_per_node 8 finetune.py --per_device_train_batch_size 16384 --per_device_eval_batch_size 16384 --use_wandb 1 --bf16 1 --dataset nomic_unsupervised --sampling_strategy cluster_within_domain --exp_name transductive-finetune-2 --num_train_epochs 3 --learning_rate 2e-6 --embedder nomic-ai/nomic-embed-text-v1-unsupervised --dataset_embedder nomic-ai/nomic-embed-text-v1-unsupervised --clustering_model gtr_base --clustering_query_to_doc 1 --automatically_deduplicate_documents 1 --automatically_deduplicate_queries 1 --arch query_independent_dt --dataset_info batch --ddp_find_unused_parameters 0 --torch_compile 0 --eval_rerank_topk 1024 --lr_scheduler_type cosine --warmup_steps 5600 --disable_dropout 1 --eval_steps 2000 --max_seq_length 512 --max_batch_size_fits_in_memory 64 --use_gc 1 --logging_steps 4 --train_cluster_size 16384 --eval_cluster_size 16384 --use_prefix 1 --transductive_corpus_size 1024 --save_steps 400 --logit_scale 50


# CUDA_VISIBLE_DEVICES=0 python finetune.py --per_device_train_batch_size 16384 --per_device_eval_batch_size 16384 --use_wandb 1 --bf16 1 --dataset nomic_unsupervised --sampling_strategy cluster_within_domain --exp_name transductive-32-bigbatch-cluster--TEST --num_train_epochs 3 --learning_rate 2e-5 --embedder nomic-ai/nomic-bert-2048 --dataset_embedder nomic-ai/nomic-bert-2048 --clustering_model gtr_base --clustering_query_to_doc 1 --automatically_deduplicate_documents 1 --automatically_deduplicate_queries 1 --arch query_independent_dt --dataset_info batch --ddp_find_unused_parameters 0 --torch_compile 0 --eval_rerank_topk 1024 --lr_scheduler_type cosine --warmup_steps 20000 --disable_dropout 1 --eval_steps 80 --max_seq_length 512 --max_batch_size_fits_in_memory 64 --use_gc 1 --logging_steps 512 --logit_scale 20.0 --train_cluster_size 16384 --eval_cluster_size 16384 --use_prefix 1 --transductive_corpus_size 1024 --use_wandb 0 --sampling_strategy random --tiny_debug 1