# biencoder
torchrun --nproc_per_node 8 finetune.py --per_device_train_batch_size 2048 --per_device_eval_batch_size 2048 --use_wandb 1 --bf16 1 --dataset nomic_unsupervised --sampling_strategy domain --exp_name biencoder-scratch-2--domain --num_train_epochs 3 --learning_rate 2e-5 --embedder nomic-ai/nomic-bert-2048 --dataset_embedder nomic-ai/nomic-bert-2048 --clustering_model gtr_base --clustering_query_to_doc 1 --automatically_deduplicate_documents 1 --automatically_deduplicate_queries 1 --arch biencoder --dataset_info batch --ddp_find_unused_parameters 0 --torch_compile 0 --eval_rerank_topk 1024 --lr_scheduler_type cosine --warmup_steps 5600 --disable_dropout 1 --eval_steps 4000 --max_seq_length 512 --max_batch_size_fits_in_memory 128 --use_gc 1 --logging_steps 20 --train_cluster_size 224 --eval_cluster_size 224 --use_prefix 1 --transductive_corpus_size 1024 --save_steps 400 --logit_scale 50 --max_eval_batches 2 --adam_beta2 0.95 --use_wandb 0 --exp_name biencoder-scratch-2--domain


# biencoder + clusters
torchrun --nproc_per_node 8 finetune.py --per_device_train_batch_size 2048 --per_device_eval_batch_size 2048 --use_wandb 1 --bf16 1 --dataset nomic_unsupervised --sampling_strategy cluster_within_domain --exp_name biencoder-scratch-2--cluster --num_train_epochs 3 --learning_rate 2e-5 --embedder nomic-ai/nomic-bert-2048 --dataset_embedder nomic-ai/nomic-bert-2048 --clustering_model gtr_base --clustering_query_to_doc 1 --automatically_deduplicate_documents 1 --automatically_deduplicate_queries 1 --arch biencoder --dataset_info batch --ddp_find_unused_parameters 0 --torch_compile 0 --eval_rerank_topk 1024 --lr_scheduler_type cosine --warmup_steps 5600 --disable_dropout 1 --eval_steps 4000 --max_seq_length 512 --max_batch_size_fits_in_memory 128 --use_gc 1 --logging_steps 20 --train_cluster_size 16384 --eval_cluster_size 16384 --use_prefix 1 --transductive_corpus_size 1024 --save_steps 400 --logit_scale 50 --max_eval_batches 2 --adam_beta2 0.95 --use_wandb 0 --exp_name biencoder-scratch-2--domain


# transductive
# torchrun --nproc_per_node 8 finetune.py --per_device_train_batch_size 16384 --per_device_eval_batch_size 16384 --use_wandb 1 --bf16 1 --dataset nomic_unsupervised --sampling_strategy cluster_within_domain --exp_name transductive-scratch-2 --num_train_epochs 3 --learning_rate 2e-5 --embedder nomic-ai/nomic-bert-2048 --dataset_embedder nomic-ai/nomic-bert-2048 --clustering_model gtr_base --clustering_query_to_doc 1 --automatically_deduplicate_documents 1 --automatically_deduplicate_queries 1 --arch query_independent_dt --dataset_info batch --ddp_find_unused_parameters 0 --torch_compile 0 --eval_rerank_topk 1024 --lr_scheduler_type cosine --warmup_steps 5600 --disable_dropout 1 --eval_steps 4000 --max_seq_length 512 --max_batch_size_fits_in_memory 64 --use_gc 1 --logging_steps 20 --train_cluster_size 224 --eval_cluster_size 224 --use_prefix 1 --transductive_corpus_size 1024 --save_steps 400 --logit_scale 50 --max_eval_batches 2 --adam_beta2 0.95
