# i'm not seeing any improvements in training loss w/ my transductive method, which should have
# 2x more params, so i think something must be wrong. i wonder if it came from ddp or gradcache
# or a bug in my code.

# BIENCODER (I know this works)
CUDA_VISIBLE_DEVICES=0 python finetune.py --per_device_train_batch_size 224 --per_device_eval_batch_size 224 --use_wandb 1 --bf16 1 --dataset nomic_unsupervised --sampling_strategy cluster_within_domain --num_train_epochs 1 --learning_rate 2e-5 --embedder nomic-ai/nomic-bert-2048 --clustering_model gtr_base --clustering_query_to_doc 1 --automatically_deduplicate_documents 1 --automatically_deduplicate_queries 1 --arch biencoder --dataset_info batch --ddp_find_unused_parameters 1 --eval_rerank_topk 512 --lr_scheduler_type inverse_sqrt --warmup_steps 1000 --disable_dropout 1 --eval_steps 12000 --max_seq_length 128 --max_batch_size_fits_in_memory 64 --use_gc 1 --logging_steps 20 --train_cluster_size 224 --eval_cluster_size 224 --use_prefix 1 --transductive_corpus_size 4 --save_steps 1000 --logit_scale 50 --max_eval_batches 4 --exp_name 2024-04-16-debug--02-biencoder

# TRANSDUCTIVE (no gc, no ddp)
CUDA_VISIBLE_DEVICES=1 python finetune.py --per_device_train_batch_size 224 --per_device_eval_batch_size 224 --use_wandb 1 --bf16 1 --dataset nomic_unsupervised --sampling_strategy cluster_within_domain --num_train_epochs 1 --learning_rate 2e-5 --embedder nomic-ai/nomic-bert-2048 --clustering_model gtr_base --clustering_query_to_doc 1 --automatically_deduplicate_documents 1 --automatically_deduplicate_queries 1 --arch query_independent_dt --dataset_info batch --ddp_find_unused_parameters 1 --eval_rerank_topk 512 --lr_scheduler_type inverse_sqrt --warmup_steps 1000 --disable_dropout 1 --eval_steps 12000 --max_seq_length 128 --max_batch_size_fits_in_memory 64 --use_gc 0 --logging_steps 20 --train_cluster_size 224 --eval_cluster_size 224 --use_prefix 1 --transductive_corpus_size 128 --save_steps 1000 --logit_scale 50 --max_eval_batches 4 --exp_name 2024-04-16-debug--02-transductive-no-gc

# TRANSDUCTIVE (yes gc)
CUDA_VISIBLE_DEVICES=2 python finetune.py --per_device_train_batch_size 224 --per_device_eval_batch_size 224 --use_wandb 1 --bf16 1 --dataset nomic_unsupervised --sampling_strategy cluster_within_domain --num_train_epochs 1 --learning_rate 2e-5 --embedder nomic-ai/nomic-bert-2048 --clustering_model gtr_base --clustering_query_to_doc 1 --automatically_deduplicate_documents 1 --automatically_deduplicate_queries 1 --arch query_independent_dt --dataset_info batch --ddp_find_unused_parameters 1 --eval_rerank_topk 512 --lr_scheduler_type inverse_sqrt --warmup_steps 1000 --disable_dropout 1 --eval_steps 12000 --max_seq_length 128 --max_batch_size_fits_in_memory 64 --use_gc 1 --logging_steps 20 --train_cluster_size 224 --eval_cluster_size 224 --use_prefix 1 --transductive_corpus_size 128 --save_steps 1000 --logit_scale 50 --max_eval_batches 4 --exp_name 2024-04-16-debug--02-transductive-gc

# TRANSDUCTIVE (yes gc, yes ddp)
CUDA_VISIBLE_DEVICES=3,4 torchrun --nproc_per_node 2 finetune.py --per_device_train_batch_size 112 --per_device_eval_batch_size 112 --use_wandb 1 --bf16 1 --dataset nomic_unsupervised --sampling_strategy cluster_within_domain --num_train_epochs 1 --learning_rate 2e-5 --embedder nomic-ai/nomic-bert-2048 --clustering_model gtr_base --clustering_query_to_doc 1 --automatically_deduplicate_documents 1 --automatically_deduplicate_queries 1 --arch query_independent_dt --dataset_info batch --ddp_find_unused_parameters 0 --eval_rerank_topk 512 --lr_scheduler_type inverse_sqrt --warmup_steps 1000 --disable_dropout 1 --eval_steps 12000 --max_seq_length 128 --max_batch_size_fits_in_memory 64 --use_gc 1 --logging_steps 20 --train_cluster_size 224 --eval_cluster_size 224 --use_prefix 1 --transductive_corpus_size 128 --save_steps 1000 --logit_scale 50 --max_eval_batches 4 --exp_name 2024-04-16-debug--02-transductive-gc-ddp-3


# TRANDUCTIVE (no gc, yes ddp)
CUDA_VISIBLE_DEVICES=5,6 torchrun --nproc_per_node 2 --master_port 12345 finetune.py --per_device_train_batch_size 112 --per_device_eval_batch_size 112 --use_wandb 1 --bf16 1 --dataset nomic_unsupervised --sampling_strategy cluster_within_domain --num_train_epochs 1 --learning_rate 2e-5 --embedder nomic-ai/nomic-bert-2048 --clustering_model gtr_base --clustering_query_to_doc 1 --automatically_deduplicate_documents 1 --automatically_deduplicate_queries 1 --arch query_independent_dt --dataset_info batch --ddp_find_unused_parameters 0 --eval_rerank_topk 512 --lr_scheduler_type inverse_sqrt --warmup_steps 1000 --disable_dropout 1 --eval_steps 12000 --max_seq_length 128 --max_batch_size_fits_in_memory 64 --use_gc 0 --logging_steps 20 --train_cluster_size 224 --eval_cluster_size 224 --use_prefix 1 --transductive_corpus_size 128 --save_steps 1000 --logit_scale 50 --max_eval_batches 4 --exp_name 2024-04-16-debug--03-transductive-nogc-ddp


# BIENCODER (no gc, yes ddp)
CUDA_VISIBLE_DEVICES=5,6 torchrun --nproc_per_node 2 --master_port 12345 finetune.py --per_device_train_batch_size 112 --per_device_eval_batch_size 112 --use_wandb 1 --bf16 1 --dataset nomic_unsupervised --sampling_strategy cluster_within_domain --num_train_epochs 1 --learning_rate 2e-5 --embedder nomic-ai/nomic-bert-2048 --clustering_model gtr_base --clustering_query_to_doc 1 --automatically_deduplicate_documents 1 --automatically_deduplicate_queries 1 --arch biencoder --dataset_info batch --ddp_find_unused_parameters 0 --eval_rerank_topk 512 --lr_scheduler_type inverse_sqrt --warmup_steps 1000 --disable_dropout 1 --eval_steps 12000 --max_seq_length 128 --max_batch_size_fits_in_memory 64 --use_gc 0 --logging_steps 20 --train_cluster_size 224 --eval_cluster_size 224 --use_prefix 1 --transductive_corpus_size 8 --save_steps 1000 --logit_scale 50 --max_eval_batches 4 --exp_name 2024-04-16-debug--01-biencoder-nogc-ddp
