CUDA_VISIBLE_DEVICES=0,1,2,3 torchrun --nproc_per_node 4 finetune.py  --per_device_train_batch_size 256 --per_device_eval_batch_size 256 --use_wandb 1 --bf16 1 --dataset nomic_supervised --sampling_strategy random --num_train_epochs 1 --learning_rate 2e-5 --embedder pile-t5-base-encoder --clustering_model gtr_base --clustering_query_to_doc 1 --automatically_deduplicate_documents 1 --automatically_deduplicate_queries 1 --arch transductive__encoder_decoder --dataset_info batch --ddp_find_unused_parameters 0 --eval_rerank_topk 256 --lr_scheduler_type constant_with_warmup --warmup_steps 5600 --disable_dropout 1 --eval_steps 1200000000000 --max_seq_length 512 --use_gc 1 --logging_steps 200 --train_cluster_size 224 --eval_cluster_size 224 --use_prefix 1 --transductive_corpus_size 256 --save_steps 16000 --logit_scale 50 --max_eval_batches 4 --exp_name 2024-04-25-supervised-pretrain-pile-t5--double--batch --ddp_share_negatives_between_gpus 0 --max_batch_size_fits_in_memory 64 --save_steps 1600 --overwrite_output_dir --use_gc 0 --max_seq_length 16 --transductive_corpus_size 16 --logging_steps 64 --torch_compile 0

##########################################################################################


CUDA_VISIBLE_DEVICES=4,5,6,7 torchrun --master_port 6547 --nproc_per_node 4 finetune.py  --per_device_train_batch_size 256 --per_device_eval_batch_size 256 --use_wandb 1 --bf16 1 --dataset nomic_supervised --sampling_strategy random --num_train_epochs 1 --learning_rate 2e-5 --embedder pile-t5-base-encoder --clustering_model gtr_base --clustering_query_to_doc 1 --automatically_deduplicate_documents 1 --automatically_deduplicate_queries 1 --arch transductive__encoder_decoder --dataset_info fake --ddp_find_unused_parameters 0 --eval_rerank_topk 256 --lr_scheduler_type constant_with_warmup --warmup_steps 5600 --disable_dropout 1 --eval_steps 1200000000000 --max_seq_length 512 --logging_steps 200 --train_cluster_size 224 --eval_cluster_size 224 --use_prefix 1 --transductive_corpus_size 256 --save_steps 16000 --logit_scale 50 --max_eval_batches 4 --exp_name 2024-04-25-supervised-pretrain-pile-t5--double--fake --ddp_share_negatives_between_gpus 0 --torch_compile 0 --save_steps 1600 --overwrite_output_dir --use_gc 0 --max_seq_length 16 --transductive_corpus_size 16 --logging_steps 64 --torch_compile 0

##########################################################################################
##########################################################################################
##########################################################################################
##########################################################################################

CUDA_VISIBLE_DEVICES=0,1,2,3 torchrun --nproc_per_node 4 finetune.py  --per_device_train_batch_size 256 --per_device_eval_batch_size 256 --use_wandb 1 --bf16 1 --dataset nomic_supervised --sampling_strategy cluster_within_domain --num_train_epochs 5 --learning_rate 2e-5 --embedder pile-t5-base-encoder --clustering_model gtr_base --clustering_query_to_doc 1 --automatically_deduplicate_documents 1 --automatically_deduplicate_queries 1 --arch transductive__encoder_decoder --dataset_info batch --ddp_find_unused_parameters 0 --eval_rerank_topk 256 --lr_scheduler_type constant_with_warmup --warmup_steps 1600 --disable_dropout 1 --eval_steps 1200000000000 --max_seq_length 512 --use_gc 1 --logging_steps 200 --train_cluster_size 224 --eval_cluster_size 224 --use_prefix 1 --transductive_corpus_size 256 --save_steps 16000 --logit_scale 50 --max_eval_batches 4 --exp_name 2024-04-25-supervised-pretrain-pile-t5--double--cluster--batch --ddp_share_negatives_between_gpus 0 --max_batch_size_fits_in_memory 64 --save_steps 1600 --overwrite_output_dir --use_gc 0 --max_seq_length 16 --transductive_corpus_size 64 --logging_steps 64 --torch_compile 0

##########################################################################################


CUDA_VISIBLE_DEVICES=4,5,6,7 torchrun --master_port 6547 --nproc_per_node 4 finetune.py  --per_device_train_batch_size 256 --per_device_eval_batch_size 256 --use_wandb 1 --bf16 1 --dataset nomic_supervised --sampling_strategy cluster_within_domain --num_train_epochs 5 --learning_rate 2e-5 --embedder pile-t5-base-encoder --clustering_model gtr_base --clustering_query_to_doc 1 --automatically_deduplicate_documents 1 --automatically_deduplicate_queries 1 --arch transductive__encoder_decoder --dataset_info fake --ddp_find_unused_parameters 0 --eval_rerank_topk 256 --lr_scheduler_type constant_with_warmup --warmup_steps 1600 --disable_dropout 1 --eval_steps 1200000000000 --max_seq_length 512 --logging_steps 200 --train_cluster_size 224 --eval_cluster_size 224 --use_prefix 1 --transductive_corpus_size 256 --save_steps 16000 --logit_scale 50 --max_eval_batches 4 --exp_name 2024-04-25-supervised-pretrain-pile-t5--double--cluster--fake --ddp_share_negatives_between_gpus 0 --torch_compile 0 --save_steps 1600 --overwrite_output_dir --use_gc 0 --max_seq_length 16 --transductive_corpus_size 64 --logging_steps 64 --torch_compile 0