# CUDA_VISIBLE_DEVICES=0,1 torchrun --nproc_per_node 2 --master_port 1230 finetune.py --per_device_train_batch_size 256 --per_device_eval_batch_size 256 --bf16 1 --use_wandb 1 --dataset nomic_unsupervised --sampling_strategy cluster_within_domain --num_train_epochs 1 --learning_rate 1e-4 --embedder pile-t5-base-encoder --clustering_model gtr_base --clustering_query_to_doc 1 --automatically_deduplicate_documents 1 --automatically_deduplicate_queries 1 --arch transductive__encoder_decoder --dataset_info batch --eval_rerank_topk 512 --use_prefix 1 --exp_name 2024-04-27-shortandtiny-test0--encdec --lr_scheduler_type constant_with_warmup --ddp_share_negatives_between_gpus 0 --use_gc 0 --max_batch_size_fits_in_memory 256 --warmup_steps 4000 --logging_steps 50 --train_cluster_size 224 --save_steps 1000 --transductive_corpus_size 64 --embedding_output_dim 16 --eval_steps 300000 --max_seq_length 32 --overwrite_output_dir --torch_compile 0 --disable_dropout 1
CUDA_VISIBLE_DEVICES=0,1 torchrun --nproc_per_node 2 --master_port 1230 finetune.py --per_device_train_batch_size 256 --per_device_eval_batch_size 256 --bf16 1 --use_wandb 1 --dataset nomic_unsupervised --sampling_strategy cluster_within_domain --num_train_epochs 1 --learning_rate 1e-4 --embedder pile-t5-base-encoder --clustering_model gtr_base --clustering_query_to_doc 1 --automatically_deduplicate_documents 1 --automatically_deduplicate_queries 1 --arch transductive__encoder_decoder --dataset_info batch --eval_rerank_topk 512 --use_prefix 1 --exp_name 2024-04-27-shortandtiny-test0--encdec--nobiencoder--meanpool --lr_scheduler_type constant_with_warmup --ddp_share_negatives_between_gpus 0 --use_gc 0 --max_batch_size_fits_in_memory 256 --warmup_steps 4000 --logging_steps 50 --train_cluster_size 224 --save_steps 1000 --transductive_corpus_size 64 --embedding_output_dim 16 --eval_steps 300000 --max_seq_length 32 --overwrite_output_dir --torch_compile 0 --disable_dropout 1

CUDA_VISIBLE_DEVICES=2,3 torchrun --nproc_per_node 2 --master_port 1231 finetune.py --per_device_train_batch_size 256 --per_device_eval_batch_size 256 --bf16 1 --use_wandb 1 --dataset nomic_unsupervised --sampling_strategy cluster_within_domain --num_train_epochs 1 --learning_rate 1e-4 --embedder gtr-base --clustering_model gtr_base --clustering_query_to_doc 1 --automatically_deduplicate_documents 1 --automatically_deduplicate_queries 1 --arch biencoder --dataset_info batch --eval_rerank_topk 512 --use_prefix 1 --exp_name 2024-04-27-shortandtiny-test0--biencoder-gtr --lr_scheduler_type constant_with_warmup --ddp_share_negatives_between_gpus 0 --use_gc 0 --max_batch_size_fits_in_memory 256 --warmup_steps 4000 --logging_steps 50 --train_cluster_size 224 --save_steps 1000 --transductive_corpus_size 64 --embedding_output_dim 16 --eval_steps 300000 --max_seq_length 32 --overwrite_output_dir --torch_compile 0 --disable_dropout 1

# CUDA_VISIBLE_DEVICES=4,5 torchrun --nproc_per_node 2 --master_port 1232 finetune.py --per_device_train_batch_size 256 --per_device_eval_batch_size 256 --bf16 1 --use_wandb 1 --dataset nomic_unsupervised --sampling_strategy cluster_within_domain --num_train_epochs 1 --learning_rate 1e-4 --embedder nomic-ai/nomic-bert-2048 --clustering_model gtr_base --clustering_query_to_doc 1 --automatically_deduplicate_documents 1 --automatically_deduplicate_queries 1 --arch biencoder --dataset_info batch --eval_rerank_topk 512 --use_prefix 1 --exp_name 2024-04-27-shortandtiny-test0--biencoder--nomicbert --lr_scheduler_type constant_with_warmup --ddp_share_negatives_between_gpus 0 --use_gc 0 --max_batch_size_fits_in_memory 256 --warmup_steps 4000 --logging_steps 50 --train_cluster_size 224 --save_steps 1000 --transductive_corpus_size 64 --embedding_output_dim 16 --eval_steps 300000 --max_seq_length 32 --overwrite_output_dir --torch_compile 0 --disable_dropout 1
CUDA_VISIBLE_DEVICES=4,5 torchrun --nproc_per_node 2 --master_port 1232 finetune.py --per_device_train_batch_size 256 --per_device_eval_batch_size 256 --bf16 1 --use_wandb 1 --dataset nomic_unsupervised --sampling_strategy cluster_within_domain --num_train_epochs 1 --learning_rate 1e-4 --embedder pile-t5-base-encoder --clustering_model gtr_base --clustering_query_to_doc 1 --automatically_deduplicate_documents 1 --automatically_deduplicate_queries 1 --arch transductive__encoder_decoder --dataset_info batch --eval_rerank_topk 512 --use_prefix 1 --exp_name 2024-04-27-shortandtiny-test0--encdec--no-relative-pos-no-biencoder --lr_scheduler_type constant_with_warmup --ddp_share_negatives_between_gpus 0 --use_gc 0 --max_batch_size_fits_in_memory 256 --warmup_steps 4000 --logging_steps 50 --train_cluster_size 224 --save_steps 1000 --transductive_corpus_size 64 --embedding_output_dim 16 --eval_steps 300000 --max_seq_length 32 --overwrite_output_dir --torch_compile 0 --disable_dropout 1

# CUDA_VISIBLE_DEVICES=6,7 torchrun --nproc_per_node 2 --master_port 1233 finetune.py --per_device_train_batch_size 256 --per_device_eval_batch_size 256 --bf16 1 --use_wandb 1 --dataset nomic_unsupervised --sampling_strategy cluster_within_domain --num_train_epochs 1 --learning_rate 1e-4 --embedder pile-t5-base-encoder --clustering_model gtr_base --clustering_query_to_doc 1 --automatically_deduplicate_documents 1 --automatically_deduplicate_queries 1 --arch transductive__encoder_decoder --dataset_info batch --eval_rerank_topk 512 --use_prefix 1 --exp_name 2024-04-27-shortandtiny-test0--encdec--no-encoder-relative-pos --lr_scheduler_type constant_with_warmup --ddp_share_negatives_between_gpus 0 --use_gc 0 --max_batch_size_fits_in_memory 256 --warmup_steps 4000 --logging_steps 50 --train_cluster_size 224 --save_steps 1000 --transductive_corpus_size 64 --embedding_output_dim 16 --eval_steps 300000 --max_seq_length 32 --overwrite_output_dir --torch_compile 0 --disable_dropout 1
CUDA_VISIBLE_DEVICES=6,7 torchrun --nproc_per_node 2 --master_port 1233 finetune.py --per_device_train_batch_size 256 --per_device_eval_batch_size 256 --bf16 1 --use_wandb 1 --dataset nomic_unsupervised --sampling_strategy cluster_within_domain --num_train_epochs 1 --learning_rate 1e-4 --embedder nomic-ai/nomic-bert-2048 --clustering_model gtr_base --clustering_query_to_doc 1 --automatically_deduplicate_documents 1 --automatically_deduplicate_queries 1 --arch transductive --dataset_info batch --eval_rerank_topk 512 --use_prefix 1 --exp_name 2024-04-27-shortandtiny-test0--transarch --lr_scheduler_type constant_with_warmup --ddp_share_negatives_between_gpus 0 --use_gc 0 --max_batch_size_fits_in_memory 256 --warmup_steps 4000 --logging_steps 50 --train_cluster_size 224 --save_steps 1000 --transductive_corpus_size 64 --embedding_output_dim 16 --eval_steps 300000 --max_seq_length 32 --overwrite_output_dir --torch_compile 0 --disable_dropout 1


# 04/28 -- 1:34 AM --
# BETTING ON MEAN-POOL NO BIENCODER ARCH W/ T5: GONNA TRAIN A LONG ONE NOW!

CUDA_VISIBLE_DEVICES=2,3,4,5 torchrun --nproc_per_node 4 --master_port 4321 finetune.py --per_device_train_batch_size 256 --per_device_eval_batch_size 256 --bf16 1 --use_wandb 1 --dataset nomic_unsupervised --sampling_strategy cluster_within_domain --num_train_epochs 1 --learning_rate 5e-5 --embedder nomic-ai/nomic-bert-2048 --clustering_model gtr_base --clustering_query_to_doc 1 --automatically_deduplicate_documents 1 --automatically_deduplicate_queries 1 --arch transductive__encoder_decoder --dataset_info batch --eval_rerank_topk 512 --use_prefix 1 --exp_name 2024-04-28-transductive-full --lr_scheduler_type constant_with_warmup --ddp_share_negatives_between_gpus 0 --use_gc 1 --max_batch_size_fits_in_memory 64 --warmup_steps 10000 --logging_steps 50 --train_cluster_size 224 --save_steps 1000 --transductive_corpus_size 256 --eval_steps 300000 --max_seq_length 512 --overwrite_output_dir --torch_compile 0 --disable_dropout 1


# 04/28 -- 11:AM well i messed that up. trying to compare to the *gg runs to see what's different
# since then. trying to enable causal and switch back to t5 and see what happens

# [1] without causal
#  [running]

# [2] with full emb
CUDA_VISIBLE_DEVICES=2,3 torchrun --nproc_per_node 2 --master_port 8764 finetune.py --per_device_train_batch_size 256 --per_device_eval_batch_size 256 --bf16 1 --use_wandb 1 --dataset nomic_unsupervised --sampling_strategy cluster_within_domain --num_train_epochs 1 --learning_rate 2e-5 --embedder pile-t5-base-encoder --clustering_model gtr_base --clustering_query_to_doc 1 --automatically_deduplicate_documents 1 --automatically_deduplicate_queries 1 --arch transductive__encoder_decoder --dataset_info batch --eval_rerank_topk 512 --use_prefix 1 --exp_name 2024-04-27-short-test0--encdec-meanpool--low-lr --lr_scheduler_type constant_with_warmup --ddp_share_negatives_between_gpus 0 --use_gc 0 --max_batch_size_fits_in_memory 256 --warmup_steps 4000 --logging_steps 50 --train_cluster_size 224 --save_steps 1000 --transductive_corpus_size 128 --eval_steps 300000 --max_seq_length 32 --overwrite_output_dir --torch_compile 0 --disable_dropout 1


# [3a] with t5/gtr (not pile-t5)
# CUDA_VISIBLE_DEVICES=4,5,6,7 torchrun --nproc_per_node 4 --master_port 8763 finetune.py --per_device_train_batch_size 256 --per_device_eval_batch_size 256 --bf16 1 --use_wandb 1 --dataset nomic_unsupervised --sampling_strategy cluster_within_domain --num_train_epochs 1 --learning_rate 1e-4 --embedder gtr-base --clustering_model gtr_base --clustering_query_to_doc 1 --automatically_deduplicate_documents 1 --automatically_deduplicate_queries 1 --arch transductive__encoder_decoder --dataset_info batch --eval_rerank_topk 512 --use_prefix 1 --exp_name 2024-04-27-shortandtiny-test--t5 --lr_scheduler_type constant_with_warmup --ddp_share_negatives_between_gpus 0 --use_gc 0 --max_batch_size_fits_in_memory 256 --warmup_steps 4000 --logging_steps 50 --train_cluster_size 224 --save_steps 1000 --transductive_corpus_size 128 --embedding_output_dim 16 --eval_steps 300000 --max_seq_length 32 --overwrite_output_dir --torch_compile 0 --disable_dropout 1

# [3.b] with full emb (biencoder)
CUDA_VISIBLE_DEVICES=4,5 torchrun --nproc_per_node 2 --master_port 8763 finetune.py --per_device_train_batch_size 256 --per_device_eval_batch_size 256 --bf16 1 --use_wandb 1 --dataset nomic_unsupervised --sampling_strategy cluster_within_domain --num_train_epochs 1 --learning_rate 1e-4 --embedder gtr-base --clustering_model gtr_base --clustering_query_to_doc 1 --automatically_deduplicate_documents 1 --automatically_deduplicate_queries 1 --arch biencoder --dataset_info batch --eval_rerank_topk 512 --use_prefix 1 --exp_name 2024-04-27-short-biencoder --lr_scheduler_type constant_with_warmup --ddp_share_negatives_between_gpus 0 --use_gc 0 --max_batch_size_fits_in_memory 256 --warmup_steps 4000 --logging_steps 50 --train_cluster_size 224 --save_steps 1000 --transductive_corpus_size 128 --eval_steps 300000 --max_seq_length 32 --overwrite_output_dir --torch_compile 0 --disable_dropout 1