# CUDA_VISIBLE_DEVICES=0,1,2,3 torchrun --nproc_per_node 4 finetune.py --per_device_train_batch_size 256 --per_device_eval_batch_size 256 --bf16 1 --use_wandb 1 --dataset nomic_unsupervised --sampling_strategy cluster_within_domain --num_train_epochs 1 --learning_rate 2e-5 --embedder nomic-ai/nomic-embed-text-v1-unsupervised --clustering_model gtr_base --clustering_query_to_doc 1 --automatically_deduplicate_documents 1 --automatically_deduplicate_queries 1 --arch biencoder --dataset_info batch --eval_rerank_topk 512 --use_prefix 1 --exp_name biencoder-tiny-pretrain-01 --num_hard_negatives 7 --lr_scheduler_type inverse_sqrt --ddp_share_negatives_between_gpus 0 --use_gc 1 --max_batch_size_fits_in_memory 256 --warmup_steps 400 --logging_steps 50 --train_cluster_size 224 --save_steps 1000 --transductive_corpus_size 224 --embedding_output_dim 16

# CUDA_VISIBLE_DEVICES=4,5,6,7 torchrun --nproc_per_node 4 --master_port 8765 finetune.py --per_device_train_batch_size 256 --per_device_eval_batch_size 256 --bf16 1 --use_wandb 1 --dataset nomic_unsupervised --sampling_strategy cluster_within_domain --num_train_epochs 1 --learning_rate 2e-5 --embedder nomic-ai/nomic-embed-text-v1-unsupervised --clustering_model gtr_base --clustering_query_to_doc 1 --automatically_deduplicate_documents 1 --automatically_deduplicate_queries 1 --arch transductive --dataset_info batch --eval_rerank_topk 512 --use_prefix 1 --exp_name transductive-tiny-pretrain-01 --num_hard_negatives 7 --lr_scheduler_type inverse_sqrt --ddp_share_negatives_between_gpus 0 --use_gc 1 --max_batch_size_fits_in_memory 128 --warmup_steps 400 --logging_steps 50 --train_cluster_size 224 --save_steps 1000 --transductive_corpus_size 224 --embedding_output_dim 16


CUDA_VISIBLE_DEVICES=0,1,2,3 torchrun --nproc_per_node 4 finetune.py --per_device_train_batch_size 256 --per_device_eval_batch_size 256 --bf16 1 --use_wandb 1 --dataset nomic_unsupervised --sampling_strategy cluster_within_domain --num_train_epochs 1 --learning_rate 2e-5 --embedder nomic-ai/nomic-bert-2048 --clustering_model gtr_base --clustering_query_to_doc 1 --automatically_deduplicate_documents 1 --automatically_deduplicate_queries 1 --arch biencoder --dataset_info batch --eval_rerank_topk 512 --use_prefix 1 --exp_name biencoder-tiny-pretrain-03 --num_hard_negatives 7 --lr_scheduler_type constant_with_warmup --ddp_share_negatives_between_gpus 0 --use_gc 1 --max_batch_size_fits_in_memory 256 --warmup_steps 400 --logging_steps 50 --train_cluster_size 224 --save_steps 1000 --transductive_corpus_size 224 --embedding_output_dim 16 --eval_steps 300000

# CUDA_VISIBLE_DEVICES=4,5,6,7 torchrun --nproc_per_node 4 --master_port 8765 finetune.py --per_device_train_batch_size 256 --per_device_eval_batch_size 256 --bf16 1 --use_wandb 1 --dataset nomic_unsupervised --sampling_strategy cluster_within_domain --num_train_epochs 1 --learning_rate 2e-5 --embedder nomic-ai/nomic-bert-2048 --clustering_model gtr_base --clustering_query_to_doc 1 --automatically_deduplicate_documents 1 --automatically_deduplicate_queries 1 --arch transductive --dataset_info batch --eval_rerank_topk 512 --use_prefix 1 --exp_name transductive-tiny-pretrain-03 --num_hard_negatives 7 --lr_scheduler_type constant_with_warmup --ddp_share_negatives_between_gpus 0 --use_gc 1 --max_batch_size_fits_in_memory 128 --warmup_steps 400 --logging_steps 50 --train_cluster_size 224 --save_steps 1000 --transductive_corpus_size 224 --embedding_output_dim 16 --eval_steps 300000
CUDA_VISIBLE_DEVICES=4,5,6,7 torchrun --nproc_per_node 4 --master_port 8765 finetune.py --per_device_train_batch_size 256 --per_device_eval_batch_size 256 --bf16 1 --use_wandb 1 --dataset nomic_unsupervised --sampling_strategy cluster_within_domain --num_train_epochs 1 --learning_rate 2e-5 --embedder nomic-ai/nomic-bert-2048 --clustering_model gtr_base --clustering_query_to_doc 1 --automatically_deduplicate_documents 1 --automatically_deduplicate_queries 1 --arch transductive__encoder_decoder --dataset_info batch --eval_rerank_topk 512 --use_prefix 1 --exp_name transductive-tiny-pretrain-03--ed --num_hard_negatives 7 --lr_scheduler_type constant_with_warmup --ddp_share_negatives_between_gpus 0 --use_gc 1 --max_batch_size_fits_in_memory 128 --warmup_steps 400 --logging_steps 50 --train_cluster_size 224 --save_steps 1000 --transductive_corpus_size 224 --embedding_output_dim 16 --eval_steps 300000
