# torchrun --nproc_per_node 8 finetune.py --per_device_train_batch_size 2048 --per_device_eval_batch_size 2048 --use_wandb 1 --bf16 1 --dataset nomic_unsupervised --sampling_strategy cluster_within_domain --num_train_epochs 1.0 --learning_rate 2e-5 --embedder nomic-ai/nomic-bert-2048 --clustering_model gtr_base --clustering_query_to_doc 1 --arch biencoder --ddp_find_unused_parameters 0 --eval_rerank_topk 256 --lr_scheduler_type linear --warmup_steps 800 --disable_dropout 1 --eval_steps 999999999999 --use_gc 0 --logging_steps 100 --train_cluster_size 224 --eval_cluster_size 224 --use_prefix 1 --save_steps 20000 --logit_scale 50 --ddp_share_negatives_between_gpus 0  --automatically_deduplicate_documents 0 --automatically_deduplicate_queries 0 --deduplication_hash_strategy random --exp_group 2024-05-14-unsup-dedup-sweep-4 --max_seq_length 32 --exp_name 2024-05-14-dedup-biencoder-none-4

# torchrun --nproc_per_node 8 finetune.py --per_device_train_batch_size 2048 --per_device_eval_batch_size 2048 --use_wandb 1 --bf16 1 --dataset nomic_unsupervised --sampling_strategy cluster_within_domain --num_train_epochs 1.0 --learning_rate 2e-5 --embedder nomic-ai/nomic-bert-2048 --clustering_model gtr_base --clustering_query_to_doc 1 --arch biencoder --ddp_find_unused_parameters 0 --eval_rerank_topk 256 --lr_scheduler_type linear --warmup_steps 800 --disable_dropout 1 --eval_steps 999999999999 --use_gc 0 --logging_steps 100 --train_cluster_size 224 --eval_cluster_size 224 --use_prefix 1 --save_steps 20000 --logit_scale 50 --ddp_share_negatives_between_gpus 0  --automatically_deduplicate_documents 1 --automatically_deduplicate_queries 0 --deduplication_hash_strategy random --exp_group 2024-05-14-unsup-dedup-sweep-4 --max_seq_length 32 --exp_name 2024-05-14-dedup-biencoder-rand-doc-4

# torchrun --nproc_per_node 8 finetune.py --per_device_train_batch_size 2048 --per_device_eval_batch_size 2048 --use_wandb 1 --bf16 1 --dataset nomic_unsupervised --sampling_strategy cluster_within_domain --num_train_epochs 1.0 --learning_rate 2e-5 --embedder nomic-ai/nomic-bert-2048 --clustering_model gtr_base --clustering_query_to_doc 1 --arch biencoder --ddp_find_unused_parameters 0 --eval_rerank_topk 256 --lr_scheduler_type linear --warmup_steps 800 --disable_dropout 1 --eval_steps 999999999999 --use_gc 0 --logging_steps 100 --train_cluster_size 224 --eval_cluster_size 224 --use_prefix 1 --save_steps 20000 --logit_scale 50 --ddp_share_negatives_between_gpus 0  --automatically_deduplicate_documents 0 --exp_group 2024-05-14-unsup-dedup-sweep-4 --automatically_deduplicate_queries 1 --deduplication_hash_strategy random --max_seq_length 32  --exp_name 2024-05-14-dedup-biencoder-rand-query-4

# torchrun --nproc_per_node 8 finetune.py --per_device_train_batch_size 2048 --per_device_eval_batch_size 2048 --use_wandb 1 --bf16 1 --dataset nomic_unsupervised --sampling_strategy cluster_within_domain --num_train_epochs 1.0 --learning_rate 2e-5 --embedder nomic-ai/nomic-bert-2048 --clustering_model gtr_base --clustering_query_to_doc 1 --arch biencoder --ddp_find_unused_parameters 0 --eval_rerank_topk 256 --lr_scheduler_type linear --warmup_steps 800 --disable_dropout 1 --eval_steps 999999999999 --use_gc 0 --logging_steps 100 --train_cluster_size 224 --eval_cluster_size 224 --use_prefix 1 --save_steps 20000 --logit_scale 50 --ddp_share_negatives_between_gpus 0  --automatically_deduplicate_documents 1 --automatically_deduplicate_queries 1 --deduplication_hash_strategy random --exp_group 2024-05-14-unsup-dedup-sweep-4 --max_seq_length 32  --exp_name 2024-05-14-dedup-biencoder-rand-both-4

torchrun --nproc_per_node 8 finetune.py --per_device_train_batch_size 2048 --per_device_eval_batch_size 2048 --use_wandb 1 --bf16 1 --dataset nomic_unsupervised --sampling_strategy cluster_within_domain --num_train_epochs 1.0 --learning_rate 2e-5 --embedder nomic-ai/nomic-bert-2048 --clustering_model gtr_base --clustering_query_to_doc 1 --arch biencoder --ddp_find_unused_parameters 0 --eval_rerank_topk 256 --lr_scheduler_type linear --warmup_steps 800 --disable_dropout 1 --eval_steps 999999999999 --use_gc 0 --logging_steps 100 --train_cluster_size 224 --eval_cluster_size 224 --use_prefix 1 --save_steps 20000 --logit_scale 50 --ddp_share_negatives_between_gpus 0  --automatically_deduplicate_documents 1 --automatically_deduplicate_queries 0 --deduplication_hash_strategy bow --exp_group 2024-05-14-unsup-dedup-sweep-4 --max_seq_length 32  --exp_name 2024-05-14-dedup-biencoder-bow-doc-4

torchrun --nproc_per_node 8 finetune.py --per_device_train_batch_size 2048 --per_device_eval_batch_size 2048 --use_wandb 1 --bf16 1 --dataset nomic_unsupervised --sampling_strategy cluster_within_domain --num_train_epochs 1.0 --learning_rate 2e-5 --embedder nomic-ai/nomic-bert-2048 --clustering_model gtr_base --clustering_query_to_doc 1 --arch biencoder --ddp_find_unused_parameters 0 --eval_rerank_topk 256 --lr_scheduler_type linear --warmup_steps 800 --disable_dropout 1 --eval_steps 999999999999 --use_gc 0 --logging_steps 100 --train_cluster_size 224 --eval_cluster_size 224 --use_prefix 1 --save_steps 20000 --logit_scale 50 --ddp_share_negatives_between_gpus 0  --automatically_deduplicate_documents 0 --exp_group 2024-05-14-unsup-dedup-sweep-4 --automatically_deduplicate_queries 1 --deduplication_hash_strategy bow --max_seq_length 32  --exp_name 2024-05-14-dedup-biencoder-bow-query-4

torchrun --nproc_per_node 8 finetune.py --per_device_train_batch_size 2048 --per_device_eval_batch_size 2048 --use_wandb 1 --bf16 1 --dataset nomic_unsupervised --sampling_strategy cluster_within_domain --num_train_epochs 1.0 --learning_rate 2e-5 --embedder nomic-ai/nomic-bert-2048 --clustering_model gtr_base --clustering_query_to_doc 1 --arch biencoder --ddp_find_unused_parameters 0 --eval_rerank_topk 256 --lr_scheduler_type linear --warmup_steps 800 --disable_dropout 1 --eval_steps 999999999999 --use_gc 0 --logging_steps 100 --train_cluster_size 224 --eval_cluster_size 224 --use_prefix 1 --save_steps 20000 --logit_scale 50 --ddp_share_negatives_between_gpus 0  --automatically_deduplicate_documents 1 --automatically_deduplicate_queries 1 --deduplication_hash_strategy bow --exp_group 2024-05-14-unsup-dedup-sweep-4 --max_seq_length 32  --exp_name 2024-05-14-dedup-biencoder-bow-both-4


# then just train the full model when we're done
torchrun --nproc_per_node 8 finetune.py --per_device_train_batch_size 256 --per_device_eval_batch_size 256 --use_wandb 1 --bf16 1 --dataset nomic_unsupervised --sampling_strategy cluster_within_domain --num_train_epochs 1 --learning_rate 5e-6 --embedder nomic-ai/nomic-bert-2048 --clustering_model gtr_base --clustering_query_to_doc 1 --automatically_deduplicate_documents 1 --automatically_deduplicate_queries 1 --arch transductive --dataset_info batch --ddp_find_unused_parameters 0 --eval_rerank_topk 128 --lr_scheduler_type linear --warmup_steps 5600 --disable_dropout 1 --eval_steps 1200000000000 --max_seq_length 512 --use_gc 1 --logging_steps 200 --train_cluster_size 224 --eval_cluster_size 224 --use_prefix 1 --transductive_corpus_size 256 --save_steps 16000 --logit_scale 50 --max_eval_batches 4 --exp_name 2024-05-14-transductive-pretrain-19 --ddp_share_negatives_between_gpus 0 --max_batch_size_fits_in_memory 128 --model_state_dict_from_path /data/saves/tti3/2024-05-01-transductive-pretrain-17 --seed 44 --transductive_sequence_dropout_prob 0.1 --deduplication_hash_strategy bow