# going to train with 32 negatives *per-gpu* for supervised training
# {domain, clustered} x {biencoder, transductive}
# torchrun --nproc_per_node 8 finetune.py --per_device_train_batch_size 32 --per_device_eval_batch_size 32 --bf16 1 --use_wandb 1 --dataset nomic_supervised --sampling_strategy cluster_within_domain --num_train_epochs 1 --learning_rate 2e-5 --embedder nomic-ai/nomic-embed-text-v1-unsupervised --clustering_model gtr_base --clustering_query_to_doc 1 --automatically_deduplicate_documents 0 --automatically_deduplicate_queries 0 --arch biencoder --dataset_info batch --eval_rerank_topk 512 --use_prefix 1 --exp_name baseline-supervised-cluster256--share --num_hard_negatives 7 --lr_scheduler_type linear --ddp_share_negatives_between_gpus 1 --use_gc 1 --max_batch_size_fits_in_memory 256 --warmup_steps 400 --logging_steps 40 --train_cluster_size 224 --save_strategy epoch --save_total_limit 1 --overwrite_output_dir

torchrun --nproc_per_node 8 finetune.py --per_device_train_batch_size 32 --per_device_eval_batch_size 32 --bf16 1 --use_wandb 1 --dataset nomic_supervised --sampling_strategy domain --num_train_epochs 1 --learning_rate 2e-5 --embedder nomic-ai/nomic-embed-text-v1-unsupervised --clustering_model gtr_base --clustering_query_to_doc 1 --automatically_deduplicate_documents 0 --automatically_deduplicate_queries 0 --arch biencoder --dataset_info batch --eval_rerank_topk 512 --use_prefix 1 --exp_name baseline-supervised-domain--share --num_hard_negatives 7 --lr_scheduler_type linear --ddp_share_negatives_between_gpus 1 --use_gc 1 --max_batch_size_fits_in_memory 256 --warmup_steps 400 --logging_steps 40 --train_cluster_size 224 --save_strategy epoch --save_total_limit 1 --overwrite_output_dir

############################################################################################

torchrun --nproc_per_node 8 finetune.py --per_device_train_batch_size 32 --per_device_eval_batch_size 32 --bf16 1 --use_wandb 1 --dataset nomic_supervised --sampling_strategy cluster_within_domain --num_train_epochs 1 --learning_rate 2e-5 --embedder nomic-ai/nomic-embed-text-v1-unsupervised --clustering_model gtr_base --clustering_query_to_doc 1 --automatically_deduplicate_documents 0 --automatically_deduplicate_queries 0 --arch transductive --dataset_info batch --eval_rerank_topk 512 --use_prefix 1 --exp_name transductive--pretrain-2epoch-supervised-cluster256--share --num_hard_negatives 7 --lr_scheduler_type linear --ddp_share_negatives_between_gpus 1 --use_gc 1 --max_batch_size_fits_in_memory 256 --warmup_steps 400 --logging_steps 40 --train_cluster_size 224 --save_strategy epoch --save_total_limit 1 --model_state_dict_from_path /data/saves/tti3/2024-05-01-transductive-pretrain-17 --transductive_corpus_size 256 --overwrite_output_dir

torchrun --nproc_per_node 8 finetune.py --per_device_train_batch_size 32 --per_device_eval_batch_size 32 --bf16 1 --use_wandb 1 --dataset nomic_supervised --sampling_strategy domain --num_train_epochs 1 --learning_rate 2e-5 --embedder nomic-ai/nomic-embed-text-v1-unsupervised --clustering_model gtr_base --clustering_query_to_doc 1 --automatically_deduplicate_documents 0 --automatically_deduplicate_queries 0 --arch transductive --dataset_info batch --eval_rerank_topk 512 --use_prefix 1 --exp_name transductive--pretrain-2epoch-supervised-domain--share --num_hard_negatives 7 --lr_scheduler_type linear --ddp_share_negatives_between_gpus 1 --use_gc 1 --max_batch_size_fits_in_memory 256 --warmup_steps 400 --logging_steps 40 --train_cluster_size 224 --save_strategy epoch --save_total_limit 1 --model_state_dict_from_path /data/saves/tti3/2024-05-01-transductive-pretrain-17 --transductive_corpus_size 256 --overwrite_output_dir