# TODO: Save configs or push to hub. Make this nicer.
ARGS_STR_DICT = {
    # this is my reimplementation of the nomic biencoder. it only trained for around 75%
    # of total training, but with a slightly higher learning rate, but i expect slightly
    # worse MTEB results here.
    # https://wandb.ai/jack-morris/tti-nomic-5/runs/1j3s5rmo/overview?nw=nwuserjxmorris12
    "unsupervised-reimpl": "--per_device_train_batch_size 2048 --per_device_eval_batch_size 2048 --use_wandb 1 --bf16 1 --dataset nomic_unsupervised --sampling_strategy domain --exp_name biencoder-scratch-3--domain --num_train_epochs 3 --learning_rate 2e-5 --embedder nomic-ai/nomic-bert-2048 --clustering_model gtr_base --clustering_query_to_doc 1 --automatically_deduplicate_documents 1 --automatically_deduplicate_queries 1 --arch biencoder --ddp_find_unused_parameters 0 --torch_compile 0 --eval_rerank_topk 1024 --lr_scheduler_type cosine --warmup_steps 5600 --disable_dropout 1 --eval_steps 10000 --max_seq_length 512 --max_batch_size_fits_in_memory 128 --use_gc 1 --logging_steps 20 --train_cluster_size 224 --eval_cluster_size 224 --use_prefix 1 --transductive_corpus_size 1024 --save_steps 4000 --logit_scale 50 --max_eval_batches 2 --adam_beta2 0.95",

    # this is my model trained with hard batching. it was trained for about two epochs,
    # maybe a bit less. it's trained longer than the baseline but we're going for SOTA
    # so i think that's allowed in this case. by accident though i trained it with 224-
    # sized clusters after 
    # https://wandb.ai/jack-morris/tti-nomic-5/runs/m44bucij/overview?nw=nwuserjxmorris12
    # "biencoder-scratch-01-cluster16k": "--per_device_train_batch_size 2048 --per_device_eval_batch_size 2048 --use_wandb 1 --bf16 1 --dataset nomic_unsupervised --sampling_strategy cluster_within_domain --num_train_epochs 1 --learning_rate 2e-5 --embedder nomic-ai/nomic-bert-2048 --clustering_model gtr_base --clustering_query_to_doc 1 --automatically_deduplicate_documents 1 --automatically_deduplicate_queries 1 --arch biencoder --ddp_find_unused_parameters 0 --torch_compile 0 --eval_rerank_topk 2048 --lr_scheduler_type inverse_sqrt --warmup_steps 5600 --disable_dropout 1 --eval_steps 10000 --max_seq_length 512 --max_batch_size_fits_in_memory 128 --use_gc 1 --logging_steps 20 --train_cluster_size 16384 --eval_cluster_size 224 --use_prefix 1 --transductive_corpus_size 1024 --save_steps 1000 --logit_scale 50 --max_eval_batches 4 --exp_name 2024-04-14-biencoder-scratch-01-cluster16k",
    # "biencoder-scratch-01-cluster224": "--per_device_train_batch_size 2048 --per_device_eval_batch_size 2048 --use_wandb 1 --bf16 1 --dataset nomic_unsupervised --sampling_strategy cluster_within_domain --num_train_epochs 1 --learning_rate 2e-5 --embedder nomic-ai/nomic-bert-2048 --clustering_model gtr_base --clustering_query_to_doc 1 --automatically_deduplicate_documents 1 --automatically_deduplicate_queries 1 --arch biencoder --ddp_find_unused_parameters 0 --torch_compile 0 --eval_rerank_topk 2048 --lr_scheduler_type inverse_sqrt --warmup_steps 5600 --disable_dropout 1 --eval_steps 10000 --max_seq_length 512 --max_batch_size_fits_in_memory 128 --use_gc 1 --logging_steps 20 --train_cluster_size 224 --eval_cluster_size 224 --use_prefix 1 --transductive_corpus_size 1024 --save_steps 1000 --logit_scale 50 --max_eval_batches 4 --exp_name 2024-04-14-biencoder-scratch-01-cluster224",
    "biencoder-scratch-02-cluster224": "--per_device_train_batch_size 224 --per_device_eval_batch_size 224 --use_wandb 1 --bf16 1 --dataset nomic_unsupervised --sampling_strategy cluster_within_domain --num_train_epochs 1 --learning_rate 2e-5 --embedder nomic-ai/nomic-bert-2048 --clustering_model gtr_base --clustering_query_to_doc 1 --automatically_deduplicate_documents 1 --automatically_deduplicate_queries 1 --arch biencoder --ddp_find_unused_parameters 0 --eval_rerank_topk 224 --lr_scheduler_type constant_with_warmup --warmup_steps 5600 --disable_dropout 1 --eval_steps 1200000000000 --max_seq_length 512 --use_gc 1 --logging_steps 200 --train_cluster_size 224 --eval_cluster_size 224 --use_prefix 1 --transductive_corpus_size 224 --save_steps 16000 --logit_scale 50 --max_eval_batches 4 --exp_name 2024-04-17-biencoder-pretrain-16 --ddp_share_negatives_between_gpus 0 --max_batch_size_fits_in_memory 128",
    "transductive-scratch-02-cluster224": "--per_device_train_batch_size 224 --per_device_eval_batch_size 224 --use_wandb 1 --bf16 1 --dataset nomic_unsupervised --sampling_strategy cluster_within_domain --num_train_epochs 1 --learning_rate 2e-5 --embedder nomic-ai/nomic-bert-2048 --clustering_model gtr_base --clustering_query_to_doc 1 --automatically_deduplicate_documents 1 --automatically_deduplicate_queries 1 --arch transductive --ddp_find_unused_parameters 0 --eval_rerank_topk 224 --lr_scheduler_type constant_with_warmup --warmup_steps 5600 --disable_dropout 1 --eval_steps 1200000000000 --max_seq_length 512 --use_gc 1 --logging_steps 200 --train_cluster_size 224 --eval_cluster_size 224 --use_prefix 1 --transductive_corpus_size 224 --save_steps 16000 --logit_scale 50 --max_eval_batches 4 --exp_name 2024-04-17-transductive-pretrain-16 --ddp_share_negatives_between_gpus 0 --max_batch_size_fits_in_memory 64",
    "transductive-scratch-02-cluster224--1.5": "--per_device_train_batch_size 256 --per_device_eval_batch_size 256 --use_wandb 1 --bf16 1 --dataset nomic_unsupervised --sampling_strategy cluster_within_domain --num_train_epochs 1 --learning_rate 1e-5 --embedder nomic-ai/nomic-bert-2048 --clustering_model gtr_base --clustering_query_to_doc 1 --automatically_deduplicate_documents 1 --automatically_deduplicate_queries 1 --arch transductive --ddp_find_unused_parameters 0 --eval_rerank_topk 128 --lr_scheduler_type linear --warmup_steps 5600 --disable_dropout 1 --eval_steps 1200000000000 --max_seq_length 512 --use_gc 1 --logging_steps 200 --train_cluster_size 224 --eval_cluster_size 224 --use_prefix 1 --transductive_corpus_size 256 --save_steps 16000 --logit_scale 50 --max_eval_batches 4 --exp_name 2024-05-01-transductive-pretrain-17 --ddp_share_negatives_between_gpus 0 --max_batch_size_fits_in_memory 96 --model_state_dict_from_path /data/saves/tti3/backup/2024-04-17-transductive-pretrain-16 --seed 43",
    "transductive-scratch-02-cluster224--2": "--per_device_train_batch_size 256 --per_device_eval_batch_size 256 --use_wandb 1 --bf16 1 --dataset nomic_unsupervised --sampling_strategy cluster_within_domain --num_train_epochs 1 --learning_rate 1e-5 --embedder nomic-ai/nomic-bert-2048 --clustering_model gtr_base --clustering_query_to_doc 1 --automatically_deduplicate_documents 1 --automatically_deduplicate_queries 1 --arch transductive --ddp_find_unused_parameters 0 --eval_rerank_topk 128 --lr_scheduler_type linear --warmup_steps 5600 --disable_dropout 1 --eval_steps 1200000000000 --max_seq_length 512 --use_gc 1 --logging_steps 200 --train_cluster_size 224 --eval_cluster_size 224 --use_prefix 1 --transductive_corpus_size 256 --save_steps 16000 --logit_scale 50 --max_eval_batches 4 --exp_name 2024-05-01-transductive-pretrain-17 --ddp_share_negatives_between_gpus 0 --max_batch_size_fits_in_memory 96 --model_state_dict_from_path /data/saves/tti3/backup/2024-04-17-transductive-pretrain-16 --seed 43",
    "transductive-scratch-02-cluster224--2.25": " --per_device_train_batch_size 64 --per_device_eval_batch_size 64 --use_wandb 1 --bf16 1 --dataset nomic_unsupervised --sampling_strategy cluster_within_domain --num_train_epochs 1 --learning_rate 1e-5 --embedder nomic-ai/nomic-bert-2048 --clustering_model gtr_base --clustering_query_to_doc 1 --automatically_deduplicate_documents 0 --automatically_deduplicate_queries 1 --arch transductive --ddp_find_unused_parameters 0 --eval_rerank_topk 128 --lr_scheduler_type linear --warmup_steps 5600 --disable_dropout 1 --eval_steps 1200000000000 --max_seq_length 512 --use_gc 1 --logging_steps 200 --train_cluster_size 224 --eval_cluster_size 224 --use_prefix 1 --transductive_corpus_size 256 --save_steps 16000 --logit_scale 50 --max_eval_batches 4 --exp_name 2024-05-05-transductive-pretrain-13 --ddp_share_negatives_between_gpus 1 --max_batch_size_fits_in_memory 96 --model_state_dict_from_path /data/saves/tti3/2024-05-01-transductive-pretrain-17 --seed 44 --overwrite_output_dir",
    "transductive-scratch-02-cluster224--3": "--per_device_train_batch_size 2048 --per_device_eval_batch_size 64 --use_wandb 1 --bf16 1 --dataset nomic_unsupervised --sampling_strategy cluster_within_domain --num_train_epochs 1 --learning_rate 2e-6 --embedder nomic-ai/nomic-bert-2048 --clustering_model gtr_base --clustering_query_to_doc 1 --automatically_deduplicate_documents 0 --automatically_deduplicate_queries 1 --arch transductive --ddp_find_unused_parameters 0 --eval_rerank_topk 128 --lr_scheduler_type linear --warmup_steps 800 --disable_dropout 1 --eval_steps 1200000000000 --max_seq_length 512 --use_gc 1 --logging_steps 40 --train_cluster_size 16384 --eval_cluster_size 224 --use_prefix 1 --transductive_corpus_size 256 --save_steps 800 --logit_scale 50 --max_eval_batches 4 --exp_name 2024-05-06-transductive-pretrain-22-16k--low-lr --ddp_share_negatives_between_gpus 1 --max_batch_size_fits_in_memory 128 --model_state_dict_from_path /data/saves/tti3/2024-05-01-transductive-pretrain-17 --seed 44 --overwrite_output_dir",
    "transductive-scratch-06-cluster224--2.8": "--per_device_train_batch_size 256 --per_device_eval_batch_size 256 --use_wandb 1 --bf16 1 --dataset nomic_unsupervised --sampling_strategy cluster_within_domain --num_train_epochs 1 --learning_rate 5e-6 --embedder nomic-ai/nomic-bert-2048 --clustering_model gtr_base --clustering_query_to_doc 1 --automatically_deduplicate_documents 1 --automatically_deduplicate_queries 1 --arch transductive --ddp_find_unused_parameters 0 --eval_rerank_topk 128 --lr_scheduler_type linear --warmup_steps 100000 --disable_dropout 1 --eval_steps 1200000000000 --max_seq_length 512 --use_gc 1 --logging_steps 160 --train_cluster_size 224 --eval_cluster_size 224 --use_prefix 1 --transductive_corpus_size 256 --save_steps 16000 --logit_scale 50 --max_eval_batches 4 --exp_name 2024-05-15-transductive-pretrain-22 --ddp_share_negatives_between_gpus 0 --max_batch_size_fits_in_memory 128 --model_state_dict_from_path /data/saves/tti3/2024-05-01-transductive-pretrain-17 --seed 45 --transductive_sequence_dropout 0.05",

    "transductive-scratch-16kdomain--1": "--per_device_train_batch_size 2048 --per_device_eval_batch_size 64 --use_wandb 1 --bf16 1 --dataset nomic_unsupervised --sampling_strategy domain --num_train_epochs 1 --learning_rate 2e-5 --embedder nomic-ai/nomic-bert-2048 --clustering_model gtr_base --clustering_query_to_doc 1 --automatically_deduplicate_documents 0 --automatically_deduplicate_queries 1 --arch transductive --ddp_find_unused_parameters 0 --eval_rerank_topk 128 --lr_scheduler_type linear --warmup_steps 800 --disable_dropout 1 --eval_steps 1200000000000 --max_seq_length 512 --use_gc 1 --logging_steps 20 --train_cluster_size 16384 --eval_cluster_size 224 --use_prefix 1 --transductive_corpus_size 256 --save_steps 800 --logit_scale 50 --max_eval_batches 4 --exp_name 2024-05-09-transductive-pretrain-16k-domain --ddp_share_negatives_between_gpus 1 --max_batch_size_fits_in_memory 128 --seed 44 --overwrite_output_dir",

    "biencoder-16cluster-4kbatch-1epoch": "--per_device_train_batch_size 512 --per_device_eval_batch_size 512 --use_wandb 1 --bf16 1 --dataset nomic_unsupervised --sampling_strategy cluster_within_domain --num_train_epochs 2 --learning_rate 2e-5 --embedder nomic-ai/nomic-bert-2048 --clustering_model gtr_base --clustering_query_to_doc 1 --automatically_deduplicate_documents 1 --automatically_deduplicate_queries 1 --arch biencoder --ddp_find_unused_parameters 0 --eval_rerank_topk 512 --lr_scheduler_type inverse_sqrt --warmup_steps 5600 --disable_dropout 1 --eval_steps 12000 --max_seq_length 512 --max_batch_size_fits_in_memory 128 --use_gc 1 --logging_steps 20 --train_cluster_size 16384 --eval_cluster_size 224 --use_prefix 1 --transductive_corpus_size 512 --save_steps 1000 --logit_scale 50 --max_eval_batches 4 --exp_name 2024-04-15-biencoder-scratch-03-cluster16k",
    "biencoder-domain-1": "--per_device_train_batch_size 4096 --per_device_eval_batch_size 512 --use_wandb 1 --bf16 1 --dataset nomic_unsupervised --sampling_strategy domain --num_train_epochs 1 --learning_rate 2e-5 --embedder nomic-ai/nomic-bert-2048 --clustering_model gtr_base --clustering_query_to_doc 1 --automatically_deduplicate_documents 1 --automatically_deduplicate_queries 1 --arch biencoder --ddp_find_unused_parameters 0 --eval_rerank_topk 512 --lr_scheduler_type inverse_sqrt --warmup_steps 5600 --disable_dropout 1 --eval_steps 12000 --max_seq_length 512 --max_batch_size_fits_in_memory 256 --use_gc 1 --logging_steps 100 --train_cluster_size 16384 --eval_cluster_size 224 --use_prefix 1 --transductive_corpus_size 512 --save_steps 1000 --logit_scale 50 --max_eval_batches 4 --exp_name 2024-04-19-biencoder-scratch-06-domain --ddp_share_negatives_between_gpus=1",
    "biencoder-domain-bs256": "--per_device_train_batch_size 64 --per_device_eval_batch_size 64 --bf16 1 --use_wandb 1 --dataset nomic_unsupervised --sampling_strategy domain --num_train_epochs 1 --learning_rate 2e-5 --embedder nomic-ai/nomic-bert-2048 --clustering_model gtr_base --clustering_query_to_doc 1 --automatically_deduplicate_documents 1 --automatically_deduplicate_queries 1 --arch biencoder --eval_rerank_topk 512 --use_prefix 1 --exp_name 2024-05-04-unsupervised-biencoder-bs256-2 --num_hard_negatives 0 --lr_scheduler_type constant_with_warmup --ddp_share_negatives_between_gpus 1 --use_gc 0 --max_batch_size_fits_in_memory 256 --warmup_steps 5600 --logging_steps 200 --save_steps 1000 --save_strategy steps --save_total_limit 1 --eval_steps 100000 --transductive_corpus_size 0",

    "supervised-baseline-domain-1epoch": "--per_device_train_batch_size 256 --per_device_eval_batch_size 256 --bf16 1 --use_wandb 1 --dataset nomic_supervised --sampling_strategy domain --num_train_epochs 1 --learning_rate 2e-5 --embedder nomic-ai/nomic-embed-text-v1-unsupervised --clustering_model gtr_base --clustering_query_to_doc 1 --automatically_deduplicate_documents 1 --automatically_deduplicate_queries 1 --arch biencoder --eval_rerank_topk 512 --use_prefix 1 --exp_name baseline-supervised-domain --num_hard_negatives 7 --lr_scheduler_type linear --ddp_share_negatives_between_gpus 0 --use_gc 1 --max_batch_size_fits_in_memory 512 --warmup_steps 400 --logging_steps 40 --train_cluster_size 224",
    "supervised-baseline-cluster224-1epoch": "--per_device_train_batch_size 256 --per_device_eval_batch_size 256 --bf16 1 --use_wandb 1 --dataset nomic_supervised --sampling_strategy cluster_within_domain --num_train_epochs 1 --learning_rate 2e-5 --embedder nomic-ai/nomic-embed-text-v1-unsupervised --clustering_model gtr_base --clustering_query_to_doc 1 --automatically_deduplicate_documents 1 --automatically_deduplicate_queries 1 --arch biencoder --eval_rerank_topk 512 --use_prefix 1 --exp_name baseline-supervised-cluster224 --num_hard_negatives 7 --lr_scheduler_type linear --ddp_share_negatives_between_gpus 0 --use_gc 1 --max_batch_size_fits_in_memory 512 --warmup_steps 400 --logging_steps 40 --train_cluster_size 224",
    "supervised-baseline-cluster224-1epoch--nodedup": "--per_device_train_batch_size 256 --per_device_eval_batch_size 256 --bf16 1 --use_wandb 1 --dataset nomic_supervised --sampling_strategy cluster_within_domain --num_train_epochs 1 --learning_rate 2e-5 --embedder nomic-ai/nomic-embed-text-v1-unsupervised --clustering_model gtr_base --clustering_query_to_doc 1 --automatically_deduplicate_documents 0 --automatically_deduplicate_queries 0 --arch biencoder --eval_rerank_topk 512 --use_prefix 1 --exp_name baseline-supervised-cluster224--no-dedup --num_hard_negatives 7 --lr_scheduler_type linear --ddp_share_negatives_between_gpus 0 --use_gc 1 --max_batch_size_fits_in_memory 256 --warmup_steps 400 --logging_steps 40 --train_cluster_size 224 --save_steps 1000",
    "supervised-baseline-cluster224-1epoch--fixdedup": "--per_device_train_batch_size 256 --per_device_eval_batch_size 256 --bf16 1 --use_wandb 1 --dataset nomic_supervised --sampling_strategy cluster_within_domain --num_train_epochs 1 --learning_rate 2e-5 --embedder nomic-ai/nomic-embed-text-v1-unsupervised --clustering_model gtr_base --clustering_query_to_doc 1 --automatically_deduplicate_documents 1 --automatically_deduplicate_queries 1 --arch biencoder --eval_rerank_topk 512 --use_prefix 1 --exp_name baseline-supervised-cluster224--no-combined-dedup --num_hard_negatives 7 --lr_scheduler_type linear --ddp_share_negatives_between_gpus 0 --use_gc 1 --max_batch_size_fits_in_memory 256 --warmup_steps 400 --logging_steps 40 --train_cluster_size 224 --save_steps 1000",
    "supervised-baseline-cluster224-1epoch--hash-dedup-query-only": "--per_device_train_batch_size 64 --per_device_eval_batch_size 64 --bf16 1 --use_wandb 1 --dataset nomic_supervised --sampling_strategy cluster_within_domain --num_train_epochs 2 --learning_rate 2e-5 --embedder nomic-ai/nomic-embed-text-v1-unsupervised --clustering_model gtr_base --clustering_query_to_doc 1 --automatically_deduplicate_documents 0 --automatically_deduplicate_queries 1 --arch biencoder --eval_rerank_topk 512 --use_prefix 1 --exp_name 2024-05-03-baseline-supervised-cluster224--hash-dedup--no-doc --num_hard_negatives 7 --lr_scheduler_type linear --ddp_share_negatives_between_gpus 1 --use_gc 1 --max_batch_size_fits_in_memory 256 --warmup_steps 400 --logging_steps 40 --train_cluster_size 224 --save_steps 1000 --save_strategy epoch --save_total_limit 2",
    "supervised-baseline-cluster224-1epoch--hash-dedup-document-only": "--per_device_train_batch_size 64 --per_device_eval_batch_size 64 --bf16 1 --use_wandb 1 --dataset nomic_supervised --sampling_strategy cluster_within_domain --num_train_epochs 2 --learning_rate 2e-5 --embedder nomic-ai/nomic-embed-text-v1-unsupervised --clustering_model gtr_base --clustering_query_to_doc 1 --automatically_deduplicate_documents 1 --automatically_deduplicate_queries 0 --arch biencoder --eval_rerank_topk 512 --use_prefix 1 --exp_name 2024-05-03-baseline-supervised-cluster224--hash-dedup--no-query --num_hard_negatives 7 --lr_scheduler_type linear --ddp_share_negatives_between_gpus 1 --use_gc 1 --max_batch_size_fits_in_memory 256 --warmup_steps 400 --logging_steps 40 --train_cluster_size 224 --save_steps 1000 --save_strategy epoch --save_total_limit 2",
    "supervised-baseline-cluster224-1epoch--hash-dedup-both": "--per_device_train_batch_size 64 --per_device_eval_batch_size 64 --bf16 1 --use_wandb 1 --dataset nomic_supervised --sampling_strategy cluster_within_domain --num_train_epochs 2 --learning_rate 2e-5 --embedder nomic-ai/nomic-embed-text-v1-unsupervised --clustering_model gtr_base --clustering_query_to_doc 1 --automatically_deduplicate_documents 1 --automatically_deduplicate_queries 1 --arch biencoder --eval_rerank_topk 512 --use_prefix 1 --exp_name 2024-05-03-baseline-supervised-cluster224--hash-dedup --num_hard_negatives 7 --lr_scheduler_type linear --ddp_share_negatives_between_gpus 1 --use_gc 1 --max_batch_size_fits_in_memory 256 --warmup_steps 400 --logging_steps 40 --train_cluster_size 224 --save_strategy epoch --save_total_limit 2",
    "supervised-baseline-cluster224-1epoch--hash-dedup-neither": "--per_device_train_batch_size 64 --per_device_eval_batch_size 64 --bf16 1 --use_wandb 1 --dataset nomic_supervised --sampling_strategy cluster_within_domain --num_train_epochs 2 --learning_rate 2e-5 --embedder nomic-ai/nomic-embed-text-v1-unsupervised --clustering_model gtr_base --clustering_query_to_doc 1 --automatically_deduplicate_documents 0 --automatically_deduplicate_queries 0 --arch biencoder --eval_rerank_topk 512 --use_prefix 1 --exp_name 2024-05-03-baseline-supervised-cluster224--hash-dedup--none --num_hard_negatives 7 --lr_scheduler_type linear --ddp_share_negatives_between_gpus 1 --use_gc 1 --max_batch_size_fits_in_memory 256 --warmup_steps 400 --logging_steps 40 --train_cluster_size 224 --save_steps 1000 --save_strategy epoch --save_strategy epoch --save_total_limit 2",

    "transductive-1epoch-supervised-cluster224-fixed": "--per_device_train_batch_size 256 --per_device_eval_batch_size 256 --bf16 1 --use_wandb 1 --dataset nomic_supervised --sampling_strategy cluster_within_domain --num_train_epochs 1 --learning_rate 2e-5 --embedder nomic-ai/nomic-embed-text-v1-unsupervised --clustering_model gtr_base --clustering_query_to_doc 1 --automatically_deduplicate_documents 1 --automatically_deduplicate_queries 1 --arch transductive --eval_rerank_topk 512 --use_prefix 1 --exp_name 2024-05-02-transductive-unsupervised-cluster224-1epoch-supervised-cluster224--FIXED-HN --overwrite_output_dir --use_wandb 1 --num_hard_negatives 7 --lr_scheduler_type linear --ddp_share_negatives_between_gpus 0 --use_gc 1 --max_batch_size_fits_in_memory 128 --warmup_steps 400 --logging_steps 50 --train_cluster_size 224 --save_steps 1000 --model_state_dict_from_path /data/saves/tti3/backup/2024-04-17-transductive-pretrain-16 --transductive_corpus_size 256",

    # transductive w/ sd
    "transductive-1epoch-supervised-cluster224-sd0.01": "--per_device_train_batch_size 256 --per_device_eval_batch_size 256 --bf16 1 --use_wandb 1 --dataset nomic_supervised --sampling_strategy cluster_within_domain --num_train_epochs 1 --learning_rate 2e-5 --embedder nomic-ai/nomic-embed-text-v1-unsupervised --clustering_model gtr_base --clustering_query_to_doc 1 --automatically_deduplicate_documents 1 --automatically_deduplicate_queries 1 --arch transductive --eval_rerank_topk 512 --use_prefix 1 --exp_name 2024-05-02-transductive-unsupervised-cluster224-1epoch-supervised-cluster224--FIXED-HN-sd0.01 --overwrite_output_dir --use_wandb 1 --num_hard_negatives 7 --lr_scheduler_type linear --ddp_share_negatives_between_gpus 0 --use_gc 1 --max_batch_size_fits_in_memory 128 --warmup_steps 400 --logging_steps 50 --train_cluster_size 224 --save_steps 1000 --model_state_dict_from_path /data/saves/tti3/backup/2024-04-17-transductive-pretrain-16 --transductive_corpus_size 256 --transductive_sequence_dropout_prob 0.01",
    "transductive-1epoch-supervised-cluster224-sd0.1": "--per_device_train_batch_size 256 --per_device_eval_batch_size 256 --bf16 1 --use_wandb 1 --dataset nomic_supervised --sampling_strategy cluster_within_domain --num_train_epochs 1 --learning_rate 2e-5 --embedder nomic-ai/nomic-embed-text-v1-unsupervised --clustering_model gtr_base --clustering_query_to_doc 1 --automatically_deduplicate_documents 1 --automatically_deduplicate_queries 1 --arch transductive --eval_rerank_topk 512 --use_prefix 1 --exp_name 2024-05-02-transductive-unsupervised-cluster224-1epoch-supervised-cluster224--FIXED-HN-sd0.1 --overwrite_output_dir --use_wandb 1 --num_hard_negatives 7 --lr_scheduler_type linear --ddp_share_negatives_between_gpus 0 --use_gc 1 --max_batch_size_fits_in_memory 128 --warmup_steps 400 --logging_steps 50 --train_cluster_size 224 --save_steps 1000 --model_state_dict_from_path /data/saves/tti3/backup/2024-04-17-transductive-pretrain-16 --transductive_corpus_size 256 --transductive_sequence_dropout_prob 0.1",
    "transductive-1epoch-supervised-cluster224-sd0.2": "--per_device_train_batch_size 256 --per_device_eval_batch_size 256 --bf16 1 --use_wandb 1 --dataset nomic_supervised --sampling_strategy cluster_within_domain --num_train_epochs 1 --learning_rate 2e-5 --embedder nomic-ai/nomic-embed-text-v1-unsupervised --clustering_model gtr_base --clustering_query_to_doc 1 --automatically_deduplicate_documents 1 --automatically_deduplicate_queries 1 --arch transductive --eval_rerank_topk 512 --use_prefix 1 --exp_name 2024-05-02-transductive-unsupervised-cluster224-1epoch-supervised-cluster224--FIXED-HN-sd0.2 --overwrite_output_dir --use_wandb 1 --num_hard_negatives 7 --lr_scheduler_type linear --ddp_share_negatives_between_gpus 0 --use_gc 1 --max_batch_size_fits_in_memory 128 --warmup_steps 400 --logging_steps 50 --train_cluster_size 224 --save_steps 1000 --model_state_dict_from_path /data/saves/tti3/backup/2024-04-17-transductive-pretrain-16 --transductive_corpus_size 256 --transductive_sequence_dropout_prob 0.2",

    # hard biencoder
    "hard-biencoder-supervised-224cluster-1epoch": "--per_device_train_batch_size 256 --per_device_eval_batch_size 256 --bf16 1 --use_wandb 1 --dataset nomic_supervised --sampling_strategy cluster_within_domain --num_train_epochs 1 --learning_rate 2e-5 --embedder nomic-ai/nomic-embed-text-v1-unsupervised --clustering_model gtr_base --clustering_query_to_doc 1 --automatically_deduplicate_documents 1 --automatically_deduplicate_queries 1 --arch transductive --eval_rerank_topk 512 --use_prefix 1 --exp_name 2024-05-03-hard-biencoder-supervised-224cluster-1epoch --overwrite_output_dir --use_wandb 1 --num_hard_negatives 7 --lr_scheduler_type linear --ddp_share_negatives_between_gpus 0 --use_gc 1 --max_batch_size_fits_in_memory 128 --warmup_steps 400 --logging_steps 50 --train_cluster_size 224 --save_steps 1000 --model_state_dict_from_path /data/saves/tti3/2024-04-15-biencoder-scratch-03-cluster16k-batch4k--1epoch",
    "hard-biencoder-supervised-domain-1epoch": "--per_device_train_batch_size 256 --per_device_eval_batch_size 256 --bf16 1 --use_wandb 1 --dataset nomic_supervised --sampling_strategy domain --num_train_epochs 1 --learning_rate 2e-5 --embedder nomic-ai/nomic-embed-text-v1-unsupervised --clustering_model gtr_base --clustering_query_to_doc 1 --automatically_deduplicate_documents 1 --automatically_deduplicate_queries 1 --arch transductive --eval_rerank_topk 512 --use_prefix 1 --exp_name 2024-05-03-hard-biencoder-supervised-domain-1epoch --overwrite_output_dir --use_wandb 1 --num_hard_negatives 7 --lr_scheduler_type linear --ddp_share_negatives_between_gpus 0 --use_gc 1 --max_batch_size_fits_in_memory 128 --warmup_steps 400 --logging_steps 50 --train_cluster_size 224 --save_steps 1000 --model_state_dict_from_path /data/saves/tti3/2024-04-15-biencoder-scratch-03-cluster16k-batch4k--1epoch",

    #########################
    # supervised sampling
    "baseline-supervised-cluster256--share-sample": "--per_device_train_batch_size 32 --per_device_eval_batch_size 32 --bf16 1 --use_wandb 1 --dataset nomic_supervised --sampling_strategy cluster_within_domain --num_train_epochs 1 --learning_rate 2e-5 --embedder nomic-ai/nomic-embed-text-v1-unsupervised --clustering_model gtr_base --clustering_query_to_doc 1 --automatically_deduplicate_documents 0 --automatically_deduplicate_queries 0 --arch biencoder --eval_rerank_topk 512 --use_prefix 1 --exp_name baseline-supervised-cluster256--share --num_hard_negatives 7 --lr_scheduler_type linear --ddp_share_negatives_between_gpus 1 --use_gc 1 --max_batch_size_fits_in_memory 256 --warmup_steps 400 --logging_steps 40 --train_cluster_size 224 --save_strategy epoch --save_total_limit 1 --overwrite_output_dir",
    ########################



    "cde": "--per_device_train_batch_size 256 --per_device_eval_batch_size 256 --use_wandb 1 --bf16 1 --dataset nomic_unsupervised --sampling_strategy cluster_within_domain --num_train_epochs 1 --learning_rate 5e-6 --embedder nomic-ai/nomic-bert-2048 --clustering_model gtr_base --clustering_query_to_doc 1 --automatically_deduplicate_documents 1 --automatically_deduplicate_queries 1 --arch transductive --ddp_find_unused_parameters 0 --eval_rerank_topk 128 --lr_scheduler_type linear --warmup_steps 100000 --disable_dropout 1 --eval_steps 1200000000000 --max_seq_length 512 --use_gc 1 --logging_steps 160 --train_cluster_size 224 --eval_cluster_size 224 --use_prefix 1 --transductive_corpus_size 256 --save_steps 16000 --logit_scale 50 --max_eval_batches 4 --exp_name 2024-05-15-transductive-pretrain-22 --ddp_share_negatives_between_gpus 0 --max_batch_size_fits_in_memory 128 --model_state_dict_from_path /data/saves/tti3/2024-05-01-transductive-pretrain-17 --seed 45 --transductive_sequence_dropout 0.05",
    "cde--no-prefix": "--per_device_train_batch_size 256 --per_device_eval_batch_size 256 --use_wandb 1 --bf16 1 --dataset nomic_unsupervised --sampling_strategy cluster_within_domain --num_train_epochs 0.5 --learning_rate 2e-5 --embedder nomic-ai/nomic-bert-2048 --clustering_model gtr_base --clustering_query_to_doc 1 --automatically_deduplicate_documents 1 --automatically_deduplicate_queries 1 --arch transductive --ddp_find_unused_parameters 0 --eval_rerank_topk 128 --lr_scheduler_type linear --warmup_steps 100000 --disable_dropout 1 --eval_steps 1200000000000 --max_seq_length 512 --use_gc 1 --logging_steps 160 --train_cluster_size 224 --eval_cluster_size 224 --use_prefix 0 --transductive_corpus_size 256 --save_steps 16000 --logit_scale 50 --max_eval_batches 4 --exp_name 2024-05-18-transductive-pretrain-22--no-prefix --ddp_share_negatives_between_gpus 0 --max_batch_size_fits_in_memory 128 --model_state_dict_from_path /data/saves/tti3/2024-05-15-transductive-pretrain-22 --seed 46 --transductive_sequence_dropout 0.05",

    "cde--supervised-1": "--per_device_train_batch_size 256 --per_device_eval_batch_size 256 --bf16 1 --use_wandb 1 --dataset nomic_supervised --sampling_strategy cluster_within_domain --num_train_epochs 3 --learning_rate 2e-5 --embedder nomic-ai/nomic-embed-text-v1-unsupervised --clustering_model gtr_base --clustering_query_to_doc 1 --automatically_deduplicate_documents 1 --automatically_deduplicate_queries 1 --arch transductive --eval_rerank_topk 512 --use_prefix 1 --exp_name 2024-05-18-transductive-2 --num_hard_negatives 7 --lr_scheduler_type linear --ddp_share_negatives_between_gpus 0 --use_gc 1 --max_batch_size_fits_in_memory 128 --warmup_steps 400 --logging_steps 40 --train_cluster_size 224 --save_strategy epoch --save_total_limit 3 --model_state_dict_from_path /data/saves/tti3/2024-05-15-transductive-pretrain-22 --transductive_corpus_size 256 --transductive_sequence_dropout_prob 0.2",
    "cde--supervised-2": "--per_device_train_batch_size 256 --per_device_eval_batch_size 256 --bf16 1 --use_wandb 1 --dataset nomic_supervised --sampling_strategy cluster_within_domain --num_train_epochs 3 --learning_rate 2e-5 --embedder nomic-ai/nomic-embed-text-v1-unsupervised --clustering_model gtr_base --clustering_query_to_doc 1 --automatically_deduplicate_documents 1 --automatically_deduplicate_queries 1 --arch transductive --eval_rerank_topk 512 --use_prefix 1 --exp_name 2024-05-18-transductive-2 --num_hard_negatives 7 --lr_scheduler_type linear --ddp_share_negatives_between_gpus 0 --use_gc 1 --max_batch_size_fits_in_memory 128 --warmup_steps 400 --logging_steps 40 --train_cluster_size 224 --save_strategy epoch --save_total_limit 3 --model_state_dict_from_path /data/saves/tti3/2024-05-15-transductive-pretrain-22 --transductive_corpus_size 256 --transductive_sequence_dropout_prob 0.2",
    "cde--supervised-3": "--per_device_train_batch_size 256 --per_device_eval_batch_size 256 --bf16 1 --use_wandb 1 --dataset nomic_supervised --sampling_strategy cluster_within_domain --num_train_epochs 3 --learning_rate 2e-5 --embedder nomic-ai/nomic-embed-text-v1-unsupervised --clustering_model gtr_base --clustering_query_to_doc 1 --automatically_deduplicate_documents 1 --automatically_deduplicate_queries 1 --arch transductive --eval_rerank_topk 512 --use_prefix 1 --exp_name 2024-05-18-transductive-2 --num_hard_negatives 7 --lr_scheduler_type linear --ddp_share_negatives_between_gpus 0 --use_gc 1 --max_batch_size_fits_in_memory 128 --warmup_steps 400 --logging_steps 40 --train_cluster_size 224 --save_strategy epoch --save_total_limit 3 --model_state_dict_from_path /data/saves/tti3/2024-05-15-transductive-pretrain-22 --transductive_corpus_size 256 --transductive_sequence_dropout_prob 0.2",
    
    "cde--no-prefix--supervised-1": "--per_device_train_batch_size 256 --per_device_eval_batch_size 256 --bf16 1 --use_wandb 1 --dataset nomic_supervised --sampling_strategy cluster_within_domain --num_train_epochs 3 --learning_rate 2e-5 --embedder nomic-ai/nomic-embed-text-v1-unsupervised --clustering_model gtr_base --clustering_query_to_doc 1 --automatically_deduplicate_documents 1 --automatically_deduplicate_queries 1 --arch transductive --eval_rerank_topk 512 --use_prefix 0 --exp_name 2024-05-18-transductive-2--no-prefix --num_hard_negatives 7 --lr_scheduler_type linear --ddp_share_negatives_between_gpus 0 --use_gc 1 --max_batch_size_fits_in_memory 128 --warmup_steps 400 --logging_steps 40 --train_cluster_size 224 --save_strategy epoch --save_total_limit 3 --model_state_dict_from_path /data/saves/tti3/2024-05-18-transductive-pretrain-22--no-prefix --transductive_corpus_size 256 --transductive_sequence_dropout_prob 0.2",
    "cde--no-prefix--supervised-2": "--per_device_train_batch_size 256 --per_device_eval_batch_size 256 --bf16 1 --use_wandb 1 --dataset nomic_supervised --sampling_strategy cluster_within_domain --num_train_epochs 3 --learning_rate 2e-5 --embedder nomic-ai/nomic-embed-text-v1-unsupervised --clustering_model gtr_base --clustering_query_to_doc 1 --automatically_deduplicate_documents 1 --automatically_deduplicate_queries 1 --arch transductive --eval_rerank_topk 512 --use_prefix 0 --exp_name 2024-05-18-transductive-2--no-prefix --num_hard_negatives 7 --lr_scheduler_type linear --ddp_share_negatives_between_gpus 0 --use_gc 1 --max_batch_size_fits_in_memory 128 --warmup_steps 400 --logging_steps 40 --train_cluster_size 224 --save_strategy epoch --save_total_limit 3 --model_state_dict_from_path /data/saves/tti3/2024-05-18-transductive-pretrain-22--no-prefix --transductive_corpus_size 256 --transductive_sequence_dropout_prob 0.2",
    "cde--no-prefix--supervised-3": "--per_device_train_batch_size 256 --per_device_eval_batch_size 256 --bf16 1 --use_wandb 1 --dataset nomic_supervised --sampling_strategy cluster_within_domain --num_train_epochs 3 --learning_rate 2e-5 --embedder nomic-ai/nomic-embed-text-v1-unsupervised --clustering_model gtr_base --clustering_query_to_doc 1 --automatically_deduplicate_documents 1 --automatically_deduplicate_queries 1 --arch transductive --eval_rerank_topk 512 --use_prefix 0 --exp_name 2024-05-18-transductive-2--no-prefix --num_hard_negatives 7 --lr_scheduler_type linear --ddp_share_negatives_between_gpus 0 --use_gc 1 --max_batch_size_fits_in_memory 128 --warmup_steps 400 --logging_steps 40 --train_cluster_size 224 --save_strategy epoch --save_total_limit 3 --model_state_dict_from_path /data/saves/tti3/2024-05-18-transductive-pretrain-22--no-prefix --transductive_corpus_size 256 --transductive_sequence_dropout_prob 0.2",
}

MODEL_FOLDER_DICT = {
    # "unsupervised-reimpl": "/home/paperspace/tti3/saves/2024-04-12-biencoder-scratch-3--domain/",
    ################################################################################################
    # "biencoder-scratch-01-cluster224": "/home/paperspace/tti3/saves/2024-04-14-biencoder-scratch-01-cluster224/",
    ################################################################################################
    "biencoder-scratch-02-cluster224": "/data/saves/tti3/2024-04-17-biencoder-pretrain-16",
    "transductive-scratch-02-cluster224": "/data/saves/tti3/backup/2024-04-17-transductive-pretrain-16",
    "transductive-scratch-02-cluster224--1.5": "/data/saves/tti3/2024-05-01-transductive-pretrain-17--half",
    "transductive-scratch-02-cluster224--2": "/data/saves/tti3/2024-05-01-transductive-pretrain-17",
    "transductive-scratch-02-cluster224--2.25": "/data/saves/tti3/2024-05-05-transductive-pretrain-13--quarter",
    "transductive-scratch-02-cluster224--3": "/data/saves/tti3/2024-05-06-transductive-pretrain-22-16k--low-lr",
    "transductive-scratch-06-cluster224--2.8": "/data/saves/tti3/2024-05-15-transductive-pretrain-22",

    "transductive-scratch-16kdomain--1": "/data/saves/tti3/2024-05-09-transductive-pretrain-16k-domain",
    ################################################################################################
    "biencoder-16cluster-4kbatch-1epoch": "/data/saves/tti3/2024-04-15-biencoder-scratch-03-cluster16k-batch4k--1epoch",
    "biencoder-domain-1": "/data/saves/tti3/2024-04-19-biencoder-scratch-06-domain/",
    "biencoder-domain-bs256": "/data/saves/tti3/2024-05-04-unsupervised-biencoder-bs256-2/",
    ################################################################################################
    # supervised sampling exps
    "baseline-supervised-cluster256--share-sample": "/data/saves/tti3/2024-05-11-baseline-supervised-cluster256--share/",
    ################################################################################################
    # baseline + supervised
    "supervised-baseline-domain-1epoch": "/data/saves/tti3/2024-04-22-baseline-supervised-domain/",

    # baseline + hardbatch
    "supervised-baseline-cluster224-1epoch": "/data/saves/tti3/2024-04-22-baseline-supervised-cluster224/",
    "supervised-baseline-cluster224-1epoch--nodedup": "/data/saves/tti3/2024-04-22-baseline-supervised-cluster224--no-dedup/",
    "supervised-baseline-cluster224-1epoch--fixdedup": "/data/saves/tti3/2024-04-22-baseline-supervised-cluster224--no-combined-dedup",
    "supervised-baseline-cluster224-1epoch--hash-dedup-query-only": "/data/saves/tti3/2024-05-03-baseline-supervised-cluster224--hash-dedup--no-doc--1epoch",
    "supervised-baseline-cluster224-1epoch--hash-dedup-document-only": "/data/saves/tti3/2024-05-03-baseline-supervised-cluster224--hash-dedup--no-query--1-epoch",
    "supervised-baseline-cluster224-1epoch--hash-dedup-both": "/data/saves/tti3/2024-05-03-baseline-supervised-cluster224--hash-dedup--1-epoch",
    "supervised-baseline-cluster224-1epoch--hash-dedup-neither": "/data/saves/tti3/2024-05-03-baseline-supervised-cluster224--hash-dedup--none--1-epoch",
    
    # transductive + Hard batch
    "transductive-1epoch-supervised-cluster224-fixed": "/data/saves/tti3/2024-05-02-transductive-unsupervised-cluster224-1epoch-supervised-cluster224--FIXED-HN",

    # transductive hard batch + hardbatch
    "hardbatch-supervised-cluster224": "/data/saves/tti3/2024-04-22-transductive-unsupervised-cluster224-1epoch-supervised-cluster224",

    # baseline reimpl + hardbatch
    "unsupervised-reimpl-supervised-cluster224": "/data/saves/tti3/2024-04-22-unsupervised-reimpl-supervised-cluster224--2",

    # transductive w/ sd
    "transductive-1epoch-supervised-cluster224-sd0.01": "/data/saves/tti3/2024-05-02-transductive-unsupervised-cluster224-1epoch-supervised-cluster224--FIXED-HN-sd0.01",
    "transductive-1epoch-supervised-cluster224-sd0.1": "/data/saves/tti3/2024-05-02-transductive-unsupervised-cluster224-1epoch-supervised-cluster224--FIXED-HN-sd0.1",
    "transductive-1epoch-supervised-cluster224-sd0.2": "/data/saves/tti3/2024-05-02-transductive-unsupervised-cluster224-1epoch-supervised-cluster224--FIXED-HN-sd0.2",

    # hard biencoder
    "hard-biencoder-supervised-224cluster-1epoch": "/data/saves/tti3/2024-05-03-hard-biencoder-supervised-224cluster-1epoch",
    "hard-biencoder-supervised-domain-1epoch": "/data/saves/tti3/2024-05-03-hard-biencoder-supervised-domain-1epoch",

    #########################

    "cde": "/data/saves/tti3/2024-05-15-transductive-pretrain-22",
    "cde--no-prefix": "/data/saves/tti3/2024-05-18-transductive-pretrain-22--no-prefix",

    "cde--supervised-1": "/data/saves/tti3/2024-05-18-transductive-2--1",
    "cde--supervised-2": "/data/saves/tti3/2024-05-18-transductive-2--2",
    "cde--supervised-3": "/data/saves/tti3/2024-05-18-transductive-2--3",

    "cde--no-prefix--supervised-1": "/data/saves/tti3/2024-05-18-transductive-2--no-prefix--1",
    "cde--no-prefix--supervised-2": "/data/saves/tti3/2024-05-18-transductive-2--no-prefix--2",
    "cde--no-prefix--supervised-3": "/data/saves/tti3/2024-05-18-transductive-2--no-prefix--3",
}
# assert ARGS_STR_DICT.keys() <= MODEL_FOLDER_DICT.keys(), f"keys not equal: {ARGS_STR_DICT.keys()} != {MODEL_FOLDER_DICT.keys()}"