datasets:
  - name: "amazon_counterfactual_classification"
    query_prefix: "classification"
    document_prefix: "classification"
  - name: "amazon_reviews_classification"
    query_prefix: "classification"
    document_prefix: "classification"
  - name: "arguana"
    query_prefix: "search_query"
    document_prefix: "search_document"
  - name: "arxiv_title"
    query_prefix: "clustering"
    document_prefix: "clustering"
  - name: "arXiv_abstract"
    query_prefix: "clustering"
    document_prefix: "clustering"
  - name: "banking_classification"
    query_prefix: "classification"
    document_prefix: "classification"
  - name: "biorxiv_abstract"
    query_prefix: "clustering"
    document_prefix: "clustering"
  - name: "biorxiv_title"
    query_prefix: "clustering"
    document_prefix: "clustering"
  - name: "eli5"
    query_prefix: "search_query"
    document_prefix: "search_document"
  - name: "emotion_classification"
    query_prefix: "classification"
    document_prefix: "classification"
  - name: "fever"
    query_prefix: "search_query"
    document_prefix: "search_document"
  - name: "fiqa"
    query_prefix: "search_query"
    document_prefix: "search_document"
  - name: "hotpotqa"
    query_prefix: "search_query"
    document_prefix: "search_document"
  - name: "imdb_classification"
    query_prefix: "classification"
    document_prefix: "classification"
  - name: "medrxiv_abstract" # ?
    query_prefix: "clustering"
    document_prefix: "clustering"
  - name: "medrxiv_title" # ?
    query_prefix: "clustering"
    document_prefix: "clustering"
  - name: "mtop_intent_classification"
    query_prefix: "classification"
    document_prefix: "classification"
  - name: "msmarco_document"
    query_prefix: "search_query"
    document_prefix: "search_document"
  - name: "msmarco_passage"
    query_prefix: "search_query"
    document_prefix: "search_document"
  - name: "nli"
    query_prefix: "classification"
    document_prefix: "classification"
  - name: "nq"
    query_prefix: "search_query"
    document_prefix: "search_document"
  - name: "quora"
    query_prefix: "search_query"
    document_prefix: "search_query"
  - name: "reddit_clustering"
    query_prefix: "clustering"
    document_prefix: "clustering"
  - name: "reddit_clusteringP2P"
    query_prefix: "clustering"
    document_prefix: "clustering"
  - name: "scidocsrr"
    query_prefix: "search_query"
    document_prefix: "search_document"
  - name: "squad"
    query_prefix: "search_query"
    document_prefix: "search_document"
  - name: "stack_exchange_clustering"
    query_prefix: "clustering"
    document_prefix: "clustering"
  - name: "stack_exchange_clusteringP2P"
    query_prefix: "clustering"
    document_prefix: "clustering"
  - name: "stack_overflow_dup_questions"
    query_prefix: "classification"
    document_prefix: "classification"
  - name: "toxic_conversations_classification"
    query_prefix: "classification"
    document_prefix: "classification"
  - name: "trivial"
    query_prefix: "search_query"
    document_prefix: "search_document"
  - name: "tweet_sentiment_extraction_classification"
    query_prefix: "classification"
    document_prefix: "classification"
  - name: "twenty_news_groups"
    query_prefix: "clustering"
    document_prefix: "clustering"